### ISSUE TITLE
Docs we want to add

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-docs#1]
Here are some docs we agreed we'd like to add. Please check off an item as you begin it, so nobody else does! (Also maybe reload first to make sure someone else didn't just check it).

- [x] Inter-linking between docs sites
    - [x] Refine verbiage of three docs site types (extension, Ðapp, user)
    - [x] Link each to each other
- [x] Quick Start Guide (build on our hackathon guide but with EIP 1102 support) 
- [x] Getting started
    - [x] 1102 Sign-in
    - [x] running ganache
    - [x] reset ganache
    - [x] Common terms
- [x] Interacting with user accounts
    - [x] Sending Transactions
        - [x] Gas price (user editable)
        - [x] Gas limit (Ðapp default editable)
        - [x] Nonce (Not Ðapp editable)
        - [x] Transaction retries (tx hash not currently an absolute source of truth!)
    - [x] Signing Data
        - [x] History
        - [x] eth_sign
        - [x] personal_sign
        - [x] eth_signTypedData
- [x] Best practices
    - [x] Detect network changes
    - [x] Add your method names to the registry
    - [x] Add your tokens to the user’s list.
- [x] Full supported JSON-RPC subset
- [x] Our experimental APIs?
    - [x] watchAsset
- [ ] how gas is calculated
- [x] #92 
  - [ ] current & planned support
  - [ ] compatible signing methods
- [ ] (soon) contract account setup / how-to
- [x] #416

**Comment by BboyAkers** [comment]
Hey! Are these still features you'd like have added to the docs? @danfinlay

**Comment by danfinlay** [comment]
These do seem like reasonable things to add. I removed a couple things that didn't match (regarding the old docs framework).
