### ISSUE TITLE
Add "see also" sections to doc pages

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1022]
Since the docs contain a lot of content that can be grouped together in different ways (e.g., by topic vs function), in addition to adding clickable doc tags (#1016) to each page, we should add a clear "See also" section to each page listing the related topic pages. We currently do reference related topic pages within the paragraphs or admonitions, but these are often overlooked and could benefit from a clear, consistent format across the docs.

**Comment by reetbatra** [comment]
Can I take this up, please?

**Comment by joaniefromtheblock** [comment]
Closing this issue as "Won't Do". We have restructured the docs to included relevant docs pages that user can use.
