### ISSUE TITLE
Edit doc item components

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1071]
Swizzle and edit various doc item components to simplify and improve the appearance of the doc page:

- Make doc tags smaller
- Make "Edit this page" smaller
- Remove paginator

**Comment by manoranjith-shankar** [comment]
Hi @alexandratran, can i work on this issue?

**Comment by alexandratran** [comment]
@manoranjith-shankar if you are familiar with [Docusaurus swizzling](https://docusaurus.io/docs/swizzling#what-is-safe-to-swizzle) and the doc item components listed in the issue, you can work on this issue.
