### ISSUE TITLE
Update Wallet Interoperability Docs Page

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-docs#1092]
I think that the "Wallet Interoperability" page on our docs is a great start to understanding EIP-6963 and Multi Injected Provider Discovery.

However, after doing much research myself and [writing an article on the subject](https://hackmd.io/LlaWBgdBTTueAdEc0u7xRA) which is my own guide for the resource I would have liked to have getting started with and understanding the ramifications, change in coding technique and overall understanding of the subject. I would like to take a shot at rewriting this page, clarifying certain points, aha moments I had myself that led me to understand how to implement in aReact + TypeScript application.

I would like to update the overall text, provide a link to a [demo that I have created](https://github.com/MetaMask/vite-react-ts-eip-6963) rather than the E2E TestDapp which I had a hard time finding the exact code that is shown in the video on the current page.

Below is a preview of the demo I plan to use instead of the video currently shown on the "Wallet Interoperability" page that I will include some audio commentary with to explain along with the visual what is going on from a users perspective.
![ScreenRecording2024-01-22at11 57 20AM-ezgif com-video-to-gif-converter](https://github.com/MetaMask/metamask-docs/assets/4899480/26bc1bbd-57f2-41f5-a140-11bb290988f8)

The demo I will link to will be more focused on just an EIP-6963 implementation in a React dapp and if a dev were to clone it and run would not have to navigate through other E2E Test dapp examples or branches to find the code they need to reproduce the same demo.

The PR will focus on 
- updating the short demo video (with audio)
- adding a link to the demo code instead of the E2E TestDapp
- revise the text on the Wallet Interoperability page
  - and any text on pages it might link to (Discover multiple wallets)

**Comment by alexandratran** [comment]
fixed by #1094
