### ISSUE TITLE
Clean up code samples

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1099]
Code samples should follow some consistent style guidelines (for example, they should be consistent regarding double vs. single quotes, trailing commas, comment style, metadata such as title, and the code should follow the programming language's style standards). This issue is to audit all code samples in the docs for consistency and style.

**Comment by FaybianB** [comment]
Hello Alexandra, may I be assigned this issue?

**Comment by alexandratran** [comment]
@FaybianB Assigned to you.
