### ISSUE TITLE
Add a Snaps architecture diagram

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1101]
Add a Snaps architecture diagram and high-level description to the overview page added in https://github.com/MetaMask/metamask-docs/pull/1098.

**Comment by Montoya** [comment]
As examples, we have these diagrams for the SDK:
https://docs.metamask.io/wallet/concepts/architecture/
https://docs.metamask.io/wallet/concepts/sdk/connections/
https://docs.metamask.io/wallet/concepts/sdk/android/
