### ISSUE TITLE
Update `wallet_addEthereumChain` Reference (Playground) Example

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-docs#1112]
The example for `wallet_addEthereumChain` currently gives the user warnings:
<img width="358" alt="Screenshot 2024-01-28 at 2 26 09 PM" src="https://github.com/MetaMask/metamask-docs/assets/4899480/407e8d1a-b533-4870-8187-00acb6569ded">

This example appears to have the correct parameters according to this link:
https://docs.gnosischain.com/tools/wallets/metamask/

That is why I have not simply submitted a PR with the correct parameters. 
It would seem that whatever logic we are using to check:

- The network name matches the chain ID
- The submitted currency symbol matches what we expect for this chain ID
- And that our records for the the submitted RPC URL matches a known provider

Is out of date or incorrect per Gnosis chain docs. We need to check the information we have stored and ensure it matches. But I am not sure which repo and PR this issue should be associated with.

**Comment by alexandratran** [comment]
According to the [Gnosis docs](https://docs.gnosischain.com/tools/wallets/metamask/#b-manual-configuration), looks like we should update the example RPC URL to `https://rpc.gnosischain.com` and symbol to `XDAI`. @joaniefromtheblock can you address this in your `api-specs` PR updating the examples?

**Comment by joaniefromtheblock** [comment]
Closed with https://github.com/MetaMask/api-specs/pull/207
