### ISSUE TITLE
Update Wallet Tutorials to include SDK and EIP-6963 how to's

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-docs#1113]
The following tutorials:

- https://docs.metamask.io/wallet/tutorials/react-dapp-local-state
- https://docs.metamask.io/wallet/tutorials/react-dapp-global-state

Need to either be updated to include using the MetaMask SDK Components or WAGMI solution.
This update would ensure that developers that find these tutorials have not only information around detecting MetaMask and connecting to it utilizing the `window.ethereum` solution, but also have the information for the easiest way to use the SDK that comes with EIP-6963 support (through the SDK and WAGMI which have both integrated and each support Multi Provider Discovery through EIP-6963)

**Comment by alexandratran** [comment]
duplicated by #1658
