### ISSUE TITLE
All the carts should be of same height

### ISSUE THREAD

**Issue by subhamkumarr** [MetaMask/metamask-docs#1133]
## Description:
The height of all the carts is not the same. All the carts should be the same.

## Screenshort:
![Screenshot (1098)](https://github.com/MetaMask/metamask-docs/assets/99977240/5c80545e-941b-4aad-9924-9a3ddebc4a3c)

**Comment by subhamkumarr** [comment]
@alexandratran, may I work on this issue, ma'am?

**Comment by alexandratran** [comment]
@subhamkumarr assigned to you. Are you still working on the other issue that you raised? (#1105). The discussion channel for MetaMask devs is in the [Consensys Discord](https://discord.gg/consensys).

**Comment by subhamkumarr** [comment]
Yes, ma'am, I'm working on this issue https://github.com/MetaMask/metamask-docs/issues/1105. This week, I will raise a PR for both issues.
