### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by subhamkumarr** [MetaMask/metamask-docs#1140]
## Description:
YouTube video integration should have a border radius for a better user experience.

## Before UI change screenshot:
![image](https://github.com/MetaMask/metamask-docs/assets/99977240/9a6f419c-ff41-4852-abd3-299d2606631f)

## After UI change screenshot:
![image](https://github.com/MetaMask/metamask-docs/assets/99977240/f8a20bce-4ed4-4b71-9d0e-fd9db7559c21)

**Comment by subhamkumarr** [comment]
@alexandratran, ma'am, if you approve this UI change. I would like to work on this.

**Comment by alexandratran** [comment]
@subhamkumarr if you can do a border radius of 3 for *all* videos in the docs (not just YouTube embeds), that would be great.

**Comment by subhamkumarr** [comment]
> @subhamkumarr if you can do a border radius of 3 for _all_ videos in the docs (not just YouTube embeds), that would be great.

OK
