### ISSUE TITLE
Update pages that reference libraries with EIP-6963 support

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#1141]
We should probably add RainbowKit to our lists of libraries with EIP-6963 support now that they've announced support in v2:
https://x.com/rainbowdotme/status/1757886864823066669?s=20

Pages to be updated:
https://docs.metamask.io/wallet/how-to/detect-wallet/multiple-wallets/
https://docs.metamask.io/wallet/concepts/wallet-interoperabilty/

**Comment by kaksv** [comment]
I have opened a pull request for this.

**Comment by alexandratran** [comment]
Fixed by #1143 and #1145.
