### ISSUE TITLE
Update Snaps code samples

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1144]
Update Snaps code samples to match guidelines used for Wallet code samples. See https://github.com/MetaMask/metamask-docs/pull/1116 for guidelines.

**Comment by subhamkumarr** [comment]
@alexandratran Can i work in this issue?

**Comment by subhamkumarr** [comment]
I raised PR for this. https://github.com/MetaMask/metamask-docs/pull/1146

**Comment by Montoya** [comment]
This may be fixed by my lint fix PR #1207

**Comment by subhamkumarr** [comment]
> This may be fixed by my lint fix PR #1207
I also tried by using format document by prettier, what wrong in that?
