### ISSUE TITLE
Reorder Wallet RPC API methods

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1148]
Reorder Wallet JSON-RPC API methods (in the [`api-specs`](https://github.com/MetaMask/api-specs) repository) in an intuitive order:

1. MetaMask `wallet_*` methods first. Within these methods:
    1. Regular `wallet_*` methods, grouped together by functionality (e.g. `*Chain` methods together and `*Permissions` methods together).
    2. Mobile methods (just `wallet_scanQRCode`)
    3. Snaps methods
2. MetaMask `eth_*` and other methods. Need to confirm that the untagged ones are indeed MetaMask-specific – if so, add the **MetaMask** tag to them. Within these methods:
    1. Regular `eth_*` methods
    2. List `personal_sign` with `eth_signTypedData_v4`
    3. Deprecated encryption methods
    4. `web3_clientVersion`
3. Standard Ethereum API methods are imported from the [`ethereum/execution-apis`](https://github.com/ethereum/execution-apis) repo and automatically tagged **Ethereum API** and appended to the list.

**Comment by joaniefromtheblock** [comment]
Proposed order?

**Chain Methods**
wallet_addEthereumChain
wallet_switchEthereumChain

**Permissions Methods**
wallet_requestPermissions
wallet_revokePermissions
wallet_getPermissions

**Asset & Onboarding Methods**
wallet_watchAsset
wallet_registerOnboarding

**Mobile Methods**
wallet_scanQRCode

**Snaps Methods**
wallet_getSnaps
wallet_requestSnaps
wallet_snap
wallet_invokeSnap

**Regular eth_* Methods**
eth_subscribe
eth_unsubscribe
eth_requestAccounts
eth_accounts
eth_sendTransaction
eth_call
eth_chainId
eth_coinbase
eth_estimateGas
eth_feeHistory
eth_gasPrice
eth_getBalance
eth_getBlockByHash
eth_getBlockByNumber
eth_getBlockReceipts
eth_getBlockTransactionCountByHash
eth_getBlockTransactionCountByNumber
eth_getCode
eth_getFilterChanges
eth_getFilterLogs
eth_getLogs
eth_getProof
eth_getStorageAt
eth_getTransactionByBlockHashAndIndex
eth_getTransactionByBlockNumberAndIndex
eth_getTransactionByHash
eth_getTransactionCount
eth_getTransactionReceipt
eth_getUncleCountByBlockHash
eth_getUncleCountByBlockNumber
eth_maxPriorityFeePerGas
eth_newBlockFilter
eth_newFilter
eth_newPendingTransactionFilter
eth_sendRawTransaction
eth_syncing
eth_uninstallFilter
eth_blockNumber

**Signature Methods**
personal_sign
eth_signTypedData_v4

**Deprecated Encryption Methods**
eth_decrypt
eth_getEncryptionPublicKey

**Other**
web3_clientVersion

**Comment by alexandratran** [comment]
The `eth_*` methods that are tagged **Ethereum API** are directly imported from [`ethereum/execution-apis`](https://github.com/ethereum/execution-apis) and automatically appended to the MetaMask list, and thus not reorder-able in `api-specs`. Those will by default be at the end.

There are some `eth_*` methods and other non-`wallet_*` methods that are specified in `api-specs` – if not already tagged with **MetaMask** you should confirm that these are indeed MetaMask-specific and add the tag. These will go above the Ethereum API methods.

**Comment by vandan** [comment]
Sorry for the late comment: I'd recommend moving the signature methods higher up, before the asset & onboarding methods.

**Comment by joaniefromtheblock** [comment]
Added your suggestion @vandan :)
