### ISSUE TITLE
Update Snaps CLI documentation

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1169]
The Snaps CLI documentation hasn't been updated since [Feb 2023](https://github.com/MetaMask/metamask-docs/commit/202ab5254f80265b24128d6c3c4eee52484199c8) and there are some configuration options that aren't documented (see [Snaps CLI](https://github.com/MetaMask/snaps/tree/main/packages/snaps-cli)). We should also give more thorough examples on how to specify options in the config file.

**Comment by Mrtenz** [comment]
When documenting this, keep in mind that the Browserify config is deprecated, and will be removed in a future version. In MetaMask/snaps#2214 we've made the Webpack config the default, and Browserify is opt-in (by specifying `bundler: 'browserify'`).
