### ISSUE TITLE
Update definition for "restricted" methods

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1195]
We currently imply that a "restricted" method is a method that requires being passed directly to `wallet_requestPermissions`:
- https://docs.metamask.io/wallet/reference/json-rpc-api/
- https://docs.metamask.io/wallet/how-to/manage-permissions/
- https://docs.metamask.io/wallet/concepts/wallet-api/#restricted-methods

Under this definition, only `eth_accounts` is restricted. We want to modify this definition to include the signature, sending, and encryption methods that are enabled via `eth_accounts`.

Something along the lines of "restricted methods are methods that cannot be called unless you have permission to do so using `wallet_requestPermissions` or `wallet_requestSnaps`." Add a note to this definition stating that acquiring the `eth_accounts` permission includes/enables calling the restricted signing/sending methods.

Also include in the description of each restricted method how to acquire the permission (either via `eth_requestAccounts` or `wallet_requestSnaps` – this is already be done for the restricted Snaps methods).

See https://github.com/MetaMask/api-specs/pull/195 for the full list of restricted methods.

**Comment by jiexi** [comment]
It would be great if we could loosen "restricted" enough to use it to describe permissioned snap methods as well

**Comment by vandan** [comment]
We'll need to specify that Snap methods that are restricted are a little different in that they need to go through [wallet_requestSnaps](https://docs.metamask.io/wallet/reference/wallet_requestsnaps/) rather than wallet_requestPermission for permissions.

**Comment by alexandratran** [comment]
Updated issue description.
