### ISSUE TITLE
Snap Dialog Prompt : Documentation correction

### ISSUE THREAD

**Issue by mario-christopher** [MetaMask/metamask-docs#1198]
There is an error in this Page which needs to be corrected.
The dialog type should not have a capital "P" for "Prompt"

![image](https://github.com/MetaMask/metamask-docs/assets/28613341/9b1da6ff-aaf0-4c38-8aef-1fecac0e166c)

**Comment by alexandratran** [comment]
Prompt dialog: https://docs.metamask.io/snaps/reference/snaps-api/#prompt-dialog

@mario-christopher Should the [alert dialog](https://docs.metamask.io/snaps/reference/snaps-api/#alert-dialog) and [confirmation dialog](https://docs.metamask.io/snaps/reference/snaps-api/#confirmation-dialog) types also not be capitalized?

**Comment by mario-christopher** [comment]
Yes @alexandratran . All should be updated in the Docs to have lower case.

![image](https://github.com/MetaMask/metamask-docs/assets/28613341/29a23122-a48d-4d23-a445-90d7efae36a8)
