### ISSUE TITLE
Create Simple Dapp Part 1 Improvements

### ISSUE THREAD

**Issue by timothius2005** [MetaMask/metamask-docs#120]
**1. Number/Letter the subheaders to correspond with the TOC**
     a. The five steps under Basic Action (Part 1) are not numbered , so it's harder for the reader to follow along in the steps. I think the bullets in the first section of Basic Action (Part 1) should be numbered, and the headers that correspond to those bullets be numbered as well.
     b. Only the first bullet point in Basic Action (Part 1) is a link to its respective section. All of the bullets should have corresponding links

**2. Avoid adding code to the middle of blocks**
As much as possible, the tutorial should try to build the code linearly. On two occasions in this tutorial, the reader is asked to add code in the middle of a block, which increases the likelihood of errors and adds confusion. 

**3. Increased feedback loops so the user can verify exactly what happened**
As a user who is fairly new to any programming language or platform, having tight feedback loops ensures that they are on the right track and boosts confidence. I would personally prefer to have less steps with more feedback, even at the expense of longer code blocks.

**4. A final code block that shows the entire page/tutorial in a single block**
At the end of the tutorial, having the entire code block on the page provides a checkpoint for the reader. They are then able to compare their work to the completed code block and make any chances to their work if they are seeing any errors. Having this larger code block also allows for the users to paste the entire code snippet and work through the tutorial with complete code .

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok
