### ISSUE TITLE
Add basic beginner tutorial

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#1202]
With removing the quickstarts and emphasizing the EIP-6963 content in #1197, we need a very basic tutorial in vanilla JS without EIP-6963 that a beginner can use as a simple learning exercise and a way to connect very quickly with minimal code and minimal background knowledge. This tutorial can include caveats that we recommend using EIP-6963 and build tools such as Vite in production.

---

This tutorial can combine the instructions from:

- This old [Set up your development environment](https://github.com/MetaMask/metamask-docs/blob/d8d2a14028dd0a61612a59dab38316c00e252e89/wallet/how-to/get-started-building/set-up-dev-environment.md) page
- [Detect MetaMask](https://docs.metamask.io/wallet/how-to/connect/detect-metamask/) using the `detect-provider` package (then remove this page from the "How to" menu to de-emphasize it)
- [Detect a user's network](https://docs.metamask.io/wallet/how-to/manage-networks/detect-network/)
- [Access a user's accounts](https://docs.metamask.io/wallet/how-to/connect/access-accounts/)

Note that in the code samples, `provider` should be replaced with `window.ethereum` since it doesn't use EIP-6963.

Make sure to provide context that this tutorial is meant to only be a learning experience for building a minimal dapp that connects to MetaMask. In production, we recommend using EIP-6963 (point to the Connect guide).

We can link to this tutorial from the intro page and in an admonition on the Connect page.

**Comment by subhamkumarr** [comment]
@alexandratran, ma'am, I want to work on this. Could you please tell me what is EIP-6963?
### These are the changes I need to do in this issue?

1. Removal of Quickstart Section: The existing Quickstart section will be removed from the documentation. 

2. Updating the "Detect Wallet" Section: This section will be renamed to "Connect to MetaMask", it will emphasize the use of EIP-6963 as the primary method for connecting to MetaMask, whether directly or through a third-party library.

3. Adding EIP-6963 Code Examples for Vanilla JS: New code examples will be added to demonstrate how to implement EIP-6963 in vanilla JavaScript.

**Comment by BboyAkers** [comment]
Oooo is this still needing to be worked on?? 👀👀👀 If so I'd be down to do it!

**Comment by alexandratran** [comment]
@BboyAkers Thanks for asking, but I think our tech writer @joaniefromtheblock is working on this. @joaniefromtheblock Can you confirm that you're currently working on this, otherwise we could give it to @BboyAkers (who has worked on this repo in the past)?
