### ISSUE TITLE
Algolia Search Doesn't work with GitHub Preview

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-docs#1290]
When testing a PR, it would be nice to have search capabilities on that update.

Currently the search function does not work in PR preview mode:

https://github.com/MetaMask/metamask-docs/assets/4899480/3d3b9b98-65ac-4dd0-b14a-290787ed5b4c

**Comment by subhamkumarr** [comment]
@alexandratran can i try to fix this issue?

**Comment by subhamkumarr** [comment]
To fix this do i need to make changes to this repo or Docusaurus?

**Comment by subhamkumarr** [comment]
@httpJunkie, it's working fine, could you please clarify for me?


https://github.com/MetaMask/metamask-docs/assets/99977240/68c38ed2-3f6d-477b-ba13-c1c7f49ea5ff

**Comment by subhamkumarr** [comment]
@httpJunkie I am interested in the issue could you please clarify me the issue

**Comment by alexandratran** [comment]
Fixed by the migration to Vercel hosting.

**Comment by Chator1** [comment]
0x84e8277c938102f42FC2D9625Fc75049A86c99Ae

في الخميس، ٢٠ يونيو ٢٠٢٤ ١٠:٤٠ م Alexandra Carrillo <
***@***.***> كتب:
