### ISSUE TITLE
Prueba Meta

### ISSUE THREAD

**Issue by alxcruz** [MetaMask/metamask-docs#1321]
Hola

**Comment by ameliasmith14** [comment]
Hola

**Comment by alxcruz** [comment]
Doctora Amelia, 
Un gusto saludarle en consideración de representación del caso de Carlos Ecija, me gustaría saber qué número de caso tiene y si podemos solicitar una llamada, el día de hoy se termina el tiempo plazo hasta las 22:00 hrs de España. Estamos pendientes de eso ya que estamos en espera de poder concretar todo este proceso con éxito, al igual que inquietos de poder retirar lo antes posible. Un abrazo.

**Comment by alxcruz** [comment]
Hola Amelia. Cancelaremos la operación. Entiendo que tenía un tiempo determinado sin embargo el usuario no pudo conseguir dicho capital. Estuvimos a la espera de respuesta para que le preste un amigo o conocido pero no logró conseguir, no sé si habría forma de conseguir una prórroga para que se consiga por lo menos algo para mantener su plazo estable. Necesito una respuesta urgente antes de que se cierre el plazo, por favor. 
Estoy al pendiente de cualquier ayuda que nos puedas brindar, entiendo que tienes una autoridad de la cual nadie puede prescindir. 
Carlos es una buena persona, se encuentra endeudado y esta es la forma más confiable que Finra puede autorizar para que retire sus fondos. Finra, incluso, puede ofrecerle un financiamiento pero necesitamos más tiempo. Claro, teniendo en consideración que a fin de mes ya se cierran todos los casos. 
Espero tu pronta respuesta, doctora, un abrazo.

**Comment by ameliasmith14** [comment]
Hola Cristal, he estado comunicándome con Carlos. Me mencionaste un financiamiento, por favor, me gustaría recibir información sobre si hay alguna manera de ayudarlo. Quedo atenta.

**Comment by alxcruz** [comment]
Buenas tardes, disculpen, el caso está cerrado.

**Comment by alxcruz** [comment]
Amelia, el caso está cerrado. Si se solicita un financiamiento, necesitaría reabrir el caso y tendría que ser aprobado. Buscaré la manera y te avisaré.

**Comment by ameliasmith14** [comment]
Gracias Cristal estoy al pendiente por favor. 
De ante mano, gracias.

**Comment by alxcruz** [comment]
Hola Amelia, como últimas noticias, Carlos menciona que un financiamiento de 2.000 USD no le sirve, por ende doy por finalizado el caso. Sólo por aclararte a ti, yo no puedo mantener el caso ya que mi trabajo se puede ver afectado por el mantenimiento de un caso donde un usuario no pudo retirar un capital.
