### ISSUE TITLE
Tab code options for yarn::npx::npm in tutorials

### ISSUE THREAD

**Issue by m4sterbunny** [MetaMask/metamask-docs#1367]
For tutorials such as https://docs.metamask.io/snaps/learn/tutorials/gas-estimation/
Simplify the page by replacing the "or" with tabs for each option.

Tab1: Yarn> yarn create @metamask/snap gas-estimation-snap
Tab2: NPX ...

**Comment by MukulKolpe** [comment]
Hey @m4sterbunny, can I work on this issue?

**Comment by MHarisAshfaq** [comment]
Hey @m4sterbunny, I have raised the [PR](https://github.com/MetaMask/metamask-docs/pull/1369). Please have a look and let me know if anything further is required.
