### ISSUE TITLE
Documentation Bug Submitter Obscures Best Practices

### ISSUE THREAD

**Issue by dotnetspec** [MetaMask/metamask-docs#14]
Google Chrome
Version 74.0.3729.169 (Official Build) (64-bit)

Can't access 'Best Practices' in the docs because the link is obscured by the Bug submitter panel and there is no option (or way) to scroll further down ...
![web 3 docs bug](https://user-images.githubusercontent.com/27340988/61678509-979c8500-ad35-11e9-9c03-cbdb5c1d7269.png)

**Comment by Siggi88** [comment]
It appears the docs were designed to be viewed maximized on a 1080p screen with little or no thought put towards people who have smaller screens.  I have to increase the size of the browser window to access the items lower in the sidebar, and not everyone has as big a screen as me.  The sidebar needs to be scrollable.

**Comment by danfinlay** [comment]
This is true. We have a totally re-styled docs site but we haven't gotten it deployed yet, will try to get this prioritized soon:

https://github.com/MetaMask/metamask-docs/tree/akers-updated

**Comment by BboyAkers** [comment]
Docs redesigned, going to close this issue 🙂
