### ISSUE TITLE
Snaps: Update screenshots on Notifications feature page to match v12 UX

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#1419]
This page: https://docs.metamask.io/snaps/features/notifications

will need to be updated to match the UX of v12

**Comment by subhamkumarr** [comment]
![image](https://github.com/user-attachments/assets/34d497b2-56e2-48bf-97b6-f8d6877d333e)

@Montoya this is the correct screenshot to replace?

**Comment by Montoya** [comment]
There's a lot more to update. It will be easier to do it when v12 of the MetaMask Extension goes live.

**Comment by subhamkumarr** [comment]
OK

**Comment by alexandratran** [comment]
Fixed by #1533
