### ISSUE TITLE
ethereum.request is not a function

### ISSUE THREAD

**Issue by valmack** [MetaMask/metamask-docs#149]
The documentation states to get accounts from this method but the method does not exist on MM injected ethereum object.

<img width="192" alt="image" src="https://user-images.githubusercontent.com/8445610/87354746-141f0980-c52d-11ea-834d-0c3a99f04b37.png">

<img width="356" alt="Screen Shot 2020-07-13 at 5 18 11 PM" src="https://user-images.githubusercontent.com/8445610/87354646-dfab4d80-c52c-11ea-8ee7-8116302b5abf.png">

**Comment by BboyAkers** [comment]
The updated documentation uses eth_requestAccounts. Does this solve this issue? 
https://docs.metamask.io/guide/rpc-api.html#eth-requestaccounts

**Comment by BboyAkers** [comment]
@valmack ⬆️  🙂

**Comment by valmack** [comment]
> The updated documentation uses eth_requestAccounts. Does this api update make the issue irrelevant?
> https://docs.metamask.io/guide/rpc-api.html#eth-requestaccounts

If the injected ethereum object does have the request method I think this should not be a problem

**Comment by BboyAkers** [comment]
I'm getting this when I run it in my browser

![window_eth_request](https://user-images.githubusercontent.com/11778717/108878907-912b5a80-75b5-11eb-9ccf-539ddbe8dc14.PNG)
