### ISSUE TITLE
Method name change

### ISSUE THREAD

**Issue by m4sterbunny** [MetaMask/metamask-docs#1491]
https://docs.metamask.io/wallet/how-to/use-sdk/mobile/android/#example-send-transaction -> Please change the method param from EthereumMethod.ETH_SEND_TRANSACTION.**** to method = the correct method should be
EthereumMethod.ETH_SEND_TRANSACTION
without  trailing .value or .amount

**Comment by alexandratran** [comment]
superseded by #1543
