### ISSUE TITLE
MERGE FREEZE: SYNC ISSUES

### ISSUE THREAD

**Issue by joaniefromtheblock** [MetaMask/metamask-docs#1508]
The following PRs (and issues mentioned) relate to content merged into the Infura repo since the start of the MM repo freeze on Aug 13th, 2024:

- [x] https://github.com/MetaMask/metamask-docs/issues/1507
-  [x] https://github.com/MetaMask/metamask-docs/issues/1501
-  [x] https://github.com/MetaMask/metamask-docs/issues/1496
-  [ ] https://github.com/INFURA/docs/pull/295
-  [ ] https://github.com/INFURA/docs/pull/294
-  [x] https://github.com/INFURA/docs/pull/278
-  [ ] https://github.com/MetaMask/metamask-docs/issues/1490

**Comment by m4sterbunny** [comment]
Some of these PRs have already been replicated (still wip) and are PRs on MM:
- https://github.com/MetaMask/metamask-docs/pull/1505
- - https://github.com/MetaMask/metamask-docs/pull/1506
