### ISSUE TITLE
Add content for Connect to Starknet

### ISSUE THREAD

**Issue by joaniefromtheblock** [MetaMask/metamask-docs#1513]

**Comment by alexandratran** [comment]
Questions about [`get-starknet`](https://github.com/starknet-io/get-starknet): Can we get more information about setting up and using `get-starknet`? The readme instructions don't really suffice.
- Do dapps still need to detect MetaMask and connect to MetaMask as usual, in addition to using the connect to Starknet wallet button?
- Can we have a full example of what this looks like in a simple dapp?
- How do devs/users access the functionality of the Starknet API methods that are rolled up in `get-starknet`?
