### ISSUE TITLE
Update screenshots for Snaps notifications how-to

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#1532]
The screenshots for this section do not match the current UI: https://docs.metamask.io/snaps/features/notifications/#2-create-a-notification

**Comment by Montoya** [comment]
Please replace with the following images: 

![notif-1](https://github.com/user-attachments/assets/fdde935d-1ed9-4798-ad52-8ec503f45fa9)

![notif-2](https://github.com/user-attachments/assets/12e79820-9268-4c26-8a4f-55d502aacbf6)

**Comment by alexandratran** [comment]
Fixed by #1533
