### ISSUE TITLE
Fix heading level opbnb?

### ISSUE THREAD

**Issue by m4sterbunny** [MetaMask/metamask-docs#1558]
Is heading level causing indentation of opbnb?

https://docs.metamask.io/services/get-started/endpoints/

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/272c14e0-1faf-4ee1-b601-44f8c1695693">

**Comment by tusharnagar17** [comment]
Hi team,
I'd like to work on this issue, could you please assign it to me?
