### ISSUE TITLE
Snaps: Add snap_getPreferences API method and update how to for localization

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#1611]
The snap_getPreferences API method is not in the API reference and the localization how to still references the old snap_getLocale

**Comment by ziad-saab** [comment]
@Montoya do we want to remove `snap_getLocale` from the docs? Or mark it as deprecated? Or leave it as is for now?

**Comment by Montoya** [comment]
@ziad-saab  Mark as deprecated
