### ISSUE TITLE
Add search indexing with Algolia

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-docs#166]
From @rekmarks:

Our documentation’s search functionality sucks, because we’re using a limited, local, markdown header-based JS search library. As it turns out, lots of big projects use VuePress for their docs like we do, and you can do a free integration with a search engine called Algolia to provide full-text site search.
The gist is that Algolia indexes your docs site, and then you incorporate their widget into your docs (very straightforward with VuePress). It does not appear to inject any trackers into the website, at least none that Brave can detect.
Users include Babel, React, Yarn, TypeScript, Webpack, and ESLint.
VuePress docs for integration: https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search
Algolia’s docsearch product home page: https://docsearch.algolia.com/

**Comment by whymarrh** [comment]
Added in #168
