### ISSUE TITLE
Document the extension-provider and its correct usage

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-docs#175]
Allows other WebExtensions to connect to MetaMask:
https://github.com/MetaMask/extension-provider

**Comment by BboyAkers** [comment]
@danfinlay want me to add and spice up the contents of the readme for that or did you have something else in mind for documenting it?

**Comment by timothius2005** [comment]
HI Team,

I'll start working on this.

Let me know if you have questions or additional input

**Comment by BboyAkers** [comment]
@timothius2005 Awesome! Thanks!

**Comment by BboyAkers** [comment]
@danfinlay @whymarrh Looks good to me but I feel like there should be better documentation regarding the MetaMask extension provider. Could ya'll elaborate on what should be added in the PR?
