### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by faid77** [MetaMask/metamask-docs#19]
Readme

**Comment by faid77** [comment]
please remove the bug on my cellphone so that I can download the metamask
on my cellphone

Pada tanggal Sel, 20 Agt 2019 22:25, Mark Stacey <notifications@github.com>
menulis:

**Comment by Gudahtt** [comment]
Hi @faid77 , this repository is for the MetaMask documentation, which you can see here: https://metamask.github.io/metamask-docs/

For help using MetaMask, visit our User Support Site: https://metamask.zendesk.com/hc/en-us
