### ISSUE TITLE
Guide - Getting Started Redesign

### ISSUE THREAD

**Issue by BboyAkers** [MetaMask/metamask-docs#190]
- [ ]  Create a visual step by step walkthrough on how to detect Web3 for [Web3 Browser Detection](https://docs.metamask.io/guide/getting-started.html#web3-browser-detection)
- [ ] Create walkthrough visuals for [Running a Test Network](https://docs.metamask.io/guide/getting-started.html#running-a-test-network)

**Comment by SaadAnsari17** [comment]
Is this done?

**Comment by Ankitvnsbihar** [comment]
can i work on this issue

**Comment by alexandratran** [comment]
The [get started section](https://docs.metamask.io/wallet/category/get-started) has been updated and re-designed in the new docs.
