### ISSUE TITLE
Code for interacting with the provider

### ISSUE THREAD

**Issue by JasperTimm** [MetaMask/metamask-docs#193]
I'm still new to Web3 development, so there's a chance I'm misunderstanding something, but I feel like the code at: https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider is incorrect.

I'm working on the best user experience for page load, with a 'connect' button for the first time users load the page calling requestAccounts. Once permission is given and the user returns/reloads the page, everything is set up without using the connect button.

So as I understand with the events, it seems like once permission is given, 'connect', 'chainChanged' and 'accountsChanged' is called on page load. Which means for the suggestion of reloading the page on 'chainChanged', you'll get into an infinite loop...

Also, having attempted to listen out for the 'connect' event on page load, I found that the param passed had no chainId and ethereum.chainId was also undefined. Is this expected? Or perhaps I was doing something wrong...

**Comment by BboyAkers** [comment]
*Once permission is given and the user returns/reloads the page, everything is set up without using the connect button.*
Correct. Once permission is given there isn't a need to use the connect button. my recommendation is to create logic that'll show 'connected' in the button and disable it.

`chainChanged`- This event when the currently connected chain changes. Here's a list of the [Chain Ids](https://docs.metamask.io/guide/ethereum-provider.html#chain-ids). To my understanding, an infinite loop shouldn't occur. I could be wrong 🙂 . Do you have a snippet of your implementation I can check out?

The [isConnected()](https://docs.metamask.io/guide/ethereum-provider.html#chain-ids) method only returns a boolean. If you're wanting to retrieve the chainId of the connected wallet.

Check out the MetaMask Test Dapp as an example.
Dapp: https://metamask.github.io/test-dapp/
Repo: https://github.com/MetaMask/test-dapp/

Hopefully this helps!
