### ISSUE TITLE
insufficient funds for transfer

### ISSUE THREAD

**Issue by LouisLiu00** [MetaMask/metamask-docs#200]
MetaMask - RPC Error: insufficient funds for transfer {code: -32000, message: "insufficient funds for transfer"}

When I sent the request, the console returned the response. At the same time, there is no wake up MetaMask plugin.
The important thing is that I cannot get any response using ".catch(error => {})". How can I get the wrong response? Please!

**Comment by BboyAkers** [comment]
Hey! It seems this might be related to the MetaMask Extension. I recommend you post your issue in that [repository](https://github.com/MetaMask/metamask-extension). If you do have a link or can re-create the issue via codesandbox or codepen. I can try to take a look at it 🙂. I'll close this issue but definitely post it in the Extension repo. If there's no response after a while please re-open this and I'll do my best to help!
