### ISSUE TITLE
Permanent "New content is available" indication

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-docs#201]
It's a small thing, but it's worth recording & fixing at some point:

<img width="247" alt="Screen Shot 2020-12-07 at 3 06 39 PM" src="https://user-images.githubusercontent.com/542863/101416048-ddf87280-389d-11eb-9a0e-1d1804fd37c4.png">

**Comment by BboyAkers** [comment]
I'll look into it 🙂

**Comment by BboyAkers** [comment]
Fixed after a vuepress update it seems 🙂
