### ISSUE TITLE
Question: Tor onion RPC connection

### ISSUE THREAD

**Issue by lekanovic** [MetaMask/metamask-docs#203]
I was wondering if it is possible to connect to a custom node that is behind Tor Onion address ? Bitcoin nodes can run behind Tor onion addresses, and many wallets support this. The benefit of this is privacy and also you do not need a internet-ip-address, Tor takes care of this

**Comment by BboyAkers** [comment]
@rekmarks You have any insight on this? 🙂

**Comment by BboyAkers** [comment]
@lekanovic I'm personally not sure myself, have you tried it yet? 🙂

**Comment by ninjavisa** [comment]
Yes I can confirm, this works

**Comment by BboyAkers** [comment]
@ninjavisa , awesome! Closing issue 🙂
