### ISSUE TITLE
Recovering account from backup files?

### ISSUE THREAD

**Issue by testoviron33** [MetaMask/metamask-docs#209]
Hi

I'm not very techie but as I feel it might be possible to recover MetaMask wallet from the backup files of the browser.
I did this locally, meaning on the same PC and user account, firstly I've created a MetaMask wallet, then I've copied the whole user folder of that chromium user, then deleted the original one and then replaced with the copy. After that the wallet was normaly working, just asking me for the local password obviously.
However when I did the same thing(even coping the whole Chromium folder) but on another machine or system account, the metamask extension didn't even appear.

Am I sensing it correctly that it still could be done somehow, but I am doing some mistake?
Do we know where the responsible files are/should be stored?

**Comment by BboyAkers** [comment]
Hey, Unfortunately I can't answer this question considering my focus is on the developer documentation. Maybe ask here? https://metamask.zendesk.com/hc/en-us
