### ISSUE TITLE
Problem finding smartphone wallet app

### ISSUE THREAD

**Issue by ICBA03** [MetaMask/metamask-docs#210]
Hello, Guys!

I have a little issue, I builded an dapp and user can interact with MetaMask wallet, but not working on finding MetaMask application on Android/iOS. Can you guys guide me with this problem?
Thanks!

**Comment by BboyAkers** [comment]
Hey! I'm not sure, is there a project repo we can look at? 🙂

**Comment by ICBA03** [comment]
Hello. Thanks for reply!
I use this trigger 
<div>
    <button class="pay-button">Deposit</button>
    <div id="status"></div>
 </div>

and this JS to open MetaMask wallet, but it only works on desktop, not on Android or iOS.


  <script type="text/javascript">
    window.addEventListener('load', async () => {
      if (window.ethereum) {
        window.web3 = new Web3(ethereum);
        try {
          await ethereum.enable();
          initPayButton()
        } catch (err) {
          $('#status').html('User denied account access', err)
        }
      } else if (window.web3) {
        window.web3 = new Web3(web3.currentProvider)
        initPayButton()
      } else {
        $('#status').html('ERROR: No Web3 Provider installed!')
      }
    })

    const initPayButton = () => {
      $('.pay-button').click(() => {
        // paymentAddress is where funds will be send to
        const paymentAddress = 'Address'
        const amountEth = 1

        web3.eth.sendTransaction({
          to: paymentAddress,
          value: web3.toWei(amountEth, 'ether')
        }, (err, transactionId) => {
          if  (err) {
            console.log('Payment failed', err)
            $('#status').html('Payment failed')
          } else {
            console.log('Payment successful', transactionId)
            $('#status').html('Payment successful')
          }
        })
      })
    }
  </script>
