### ISSUE TITLE
React native dapp is not opening metamask mobile to sign transaction...

### ISSUE THREAD

**Issue by Hammad-Mubeen** [MetaMask/metamask-docs#211]
This code is not working (does not open my metamask wallet, instead does nothing)..where i am wrong??...what code will make this magic happen?...i can't be totally wrong because i have followed metamask official documentation (walletconnect and providers API)  
if(window.ethereum) {
          await window.ethereum.enable();
          provider = new ethers.providers.Web3Provider(window.ethereum);
          publicAddress = window.ethereum.selectedAddress;
      } else {
        try {
          const providerOptions = {
            walletconnect: {
                package:  window.WalletConnectProvider.default,
                options: {
                    infuraId: '1a80ae6328714bedac40b8b665d7cb34',
                }
            }
        };
        web3Modal = new window.Web3Modal.default({
            cacheProvider: false,
            providerOptions,
            disableInjectedProvider: false
        });
        provider = await web3Modal.connect();
        publicAddress = provider.accounts[0];
        } catch (e) {
        
        }

**Comment by BboyAkers** [comment]
Just for clarification, you're following the metamask documentation on walletconnect not the offical metamask documentation from docs.metamask.io, correct?

**Comment by majorarif** [comment]
Hello, Did you get a solution?

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
No

**Comment by alexandratran** [comment]
Closing due to no response, and the code provided uses deprecated methods.
