### ISSUE TITLE
Provide working examples of message signing now that the old MetaMask API is deprecated

### ISSUE THREAD

**Issue by pcowgill** [MetaMask/metamask-docs#212]
The [repo](https://github.com/danfinlay/js-eth-personal-sign-examples) that is linked to [here in the docs](https://docs.metamask.io/guide/signing-data.html) uses the old web3 API, so the live examples are no longer functional.

This would be a big help if you get a chance to update this. Thanks! If it's easier to add, screenshots of what the MetaMask prompt looks like for each signing method would be great too.

Related issue https://github.com/danfinlay/js-eth-personal-sign-examples/issues/19

**Comment by BboyAkers** [comment]
I'll dig into it!

**Comment by BboyAkers** [comment]
Current WIP 🙂 

https://github.com/danfinlay/js-eth-personal-sign-examples/pull/20

**Comment by alexandratran** [comment]
The [new signing data docs](https://docs.metamask.io/wallet/how-to/sign-data) have source code and live examples for the recommended signing methods.
