### ISSUE TITLE
Documentation URL's broken

### ISSUE THREAD

**Issue by Ridnois** [MetaMask/metamask-docs#217]
I have found that most of the links that are inside the documentation itself are broken and are easily fixeable.

by example, look at this
![image](https://user-images.githubusercontent.com/23710929/105791152-4db4e080-5f64-11eb-88d0-4f2529f872ab.png)
> The **Migration Guide** links to _https://docs.metamask.io/guide/guide/provider-migration.html_, which should be _https://docs.metamask.io/guide/provider-migration.html_

As you can see, the guide route is repeated. that's all that has to be solved!

**Comment by BboyAkers** [comment]
Thanks for catching this! 🙂 I'll go through and update them! Feel free to post more under this thread.

**Comment by BboyAkers** [comment]
I'd also be happy to help you get a PR in if you want to help fix it!

**Comment by Ridnois** [comment]
> I'd also be happy to help you get a PR in if you want to fix 
It would be my honor, if you have documentation about the PR style and description needed, i'd appreciate that you could share more info to help.

**Comment by BboyAkers** [comment]
It looks like there was a PR for the fix but I'd be happy to assign you something else you might like to get a different PR in 🙂
