### ISSUE TITLE
How to connect my dapp to metamask wallet?

### ISSUE THREAD

**Issue by montaigne2100** [MetaMask/metamask-docs#224]
Hi everyone, I am trying to develop a dapp(for android and ios) and I want to connect my metamask wallet to my app. But i have no idea how to it. Can you guys help me?

**Comment by utkarshg6** [comment]
Hi, @montaigne2100. I am also a fellow Dapp developer. I used this part of the documentation. [Create a Simple Dapp](https://docs.metamask.io/guide/create-dapp.html) for building my Dapp. You can even clone the code if you want for a deeper understanding.

**Comment by BboyAkers** [comment]
@utkarshg6 thanks for point that out! 🙂 As for using MetaMask in your mobile app. I'm not entirely sure myself. It sounds more along the lines of you wanting to connect to the Ethereum blockchain more than anything. I'll ask/look around and get back to you later this week!

**Comment by BboyAkers** [comment]
@montaigne2100 Question. Have you looked into this? https://docs.metamask.io/guide/mobile-best-practices.html#using-walletconnect

**Comment by montaigne2100** [comment]
@utkarshg6   @BboyAkers  Thanks a lot for answers :) I checked all the links you posted, but couldn't get it exactly. Basically what I want is, get the user's wallet public id. I am able to navigate the user to metamask with a walletconnect deeplink, but I can't send a connect wallet request. [https://i.stack.imgur.com/G5Thz.jpg](Like Zerion) How can I achieve this?

**Comment by BboyAkers** [comment]
@montaigne2100 Would this be what you're looking for? 🙂 
https://docs.metamask.io/guide/getting-started.html#connecting-to-metamask
