### ISSUE TITLE
Eth from test faucet will only get sent to a single account

### ISSUE THREAD

**Issue by DSwan23** [MetaMask/metamask-docs#234]
Hello,

I have two accounts currently and I was trying to receive some Eth from the Ropsten test faucet. I selected the account that I wanted to send the Eth to, let's call this account 1. I then made sure that I was on the Ropsten test network, I clicked on the 'Buy' button on the screen where I chose the test faucet option from the menu that appeared. This redirected me to the https://faucet.metamask.io/ site where I selected to receive one Eth. This Eth was sent to my other account, account 2. Upon further inspection, I noticed that the account number on the faucet site was, in fact, the second account address. Since there is no way I can enter my own address into this site, is there a workaround for this? If not, could you look into fixing this? If this is not the place for this issue let me know where I can send it through the proper channels.

Thanks,
-- Doug

**Comment by BboyAkers** [comment]
This may answer your question!
https://ethereum.stackexchange.com/questions/86901/how-can-i-disconnect-a-metamask-wallet-from-uniswap#:~:text=You%20can%20disconnect%20a%20Metamask,with%20the%20trash%20can%20icon.
