### ISSUE TITLE
Equivalent to web3's call() function

### ISSUE THREAD

**Issue by PapitoMyKing** [MetaMask/metamask-docs#237]
This isn't really an issue but a question.

I cannot find anywhere on the docs how to make a call to a smart contract and only read data, like web3's call(). Can someone point to the right direction? Thanks!

**Comment by BboyAkers** [comment]
Try taking a look inside the MetaMask Test Dapp. Let me know if this helps! 🙂 
https://github.com/MetaMask/test-dapp/blob/main/src/index.js#L88
