### ISSUE TITLE
Outdated documentation on `eth_sign`

### ISSUE THREAD

**Issue by joelamouche** [MetaMask/metamask-docs#239]
https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask

The current documentation says that `eth_sign` is exposed, allowing DApps to sign arbitrary code.
If I'm not mistaken, that isn't true since https://github.com/ethereum/go-ethereum/pull/2940 : now `eth_sign` prepends the signed data with a string like `personnal_sign` does.

This is important for me because I need this `eth_sign` function as it was before in order to sign transactions for Moonbeam, an EVM-compatible parachain based on substrate (polkadot)

**Comment by BboyAkers** [comment]
So There are different version of Eth Signing. Try Pulling this PR down and check the code out. Hopefully this helps.
https://github.com/danfinlay/js-eth-personal-sign-examples/pull/20

**Comment by danfinlay** [comment]
This is not actually true. Unfortunately, while geth decided to make that change, MetaMask was already supporting applications in production that depended on this method, so we addressed the security with an increasingly salient warning. https://docs.metamask.io/guide/signing-data.html#a-brief-history

**Comment by joelamouche** [comment]
@danfinlay Thank you for the clarification.
However, there is something else that I would like you to clarify:
- Are all signature functions in the extension coming from `https://github.com/MetaMask/eth-sig-util` ?
- If that's true, where can I find the `eth_sign` signature function in that package?

Thanks in advance

**Comment by joelamouche** [comment]
@danfinlay I was wondering if you could point me to the implementation of `eth_sign` please

**Comment by joelamouche** [comment]
Also this documentation says the message is prefixed as well : https://eth.wiki/json-rpc/API#eth_sign
