### ISSUE TITLE
Deeplink docs missing

### ISSUE THREAD

**Issue by matheus-gsilva-ifood** [MetaMask/metamask-docs#244]
Hello!
Where can i find examples and docs for deeplink? I've tried to find on `metamask-mobile` as well but I could not! Where can I find docs or even examples?

Thank you!

**Comment by BboyAkers** [comment]
Hey! What examples in particular were you looking for? 🙂 I'd be more than happy to try to create them. 
Did this link help at all?
https://docs.metamask.io/guide/mobile-best-practices.html#deeplinking

**Comment by matheus-gsilva-ifood** [comment]
Hi! 
i would like to:
1. be able to register into my app using metamask login (similar to a connection that a dapp would do).
2. Payment/contract interaction going from my app to metamask window (so user can accept, change gas, etc) and a callback into my app again
3. Retriever balance of specific tokens from the account connected on step 1

**Comment by BboyAkers** [comment]
I'll dig into this and see if I can create a tutorial. I'll be stacked for the next few weeks with several conference talks, work, and life, as a heads up. I'll make sure to re-visit this soon after my schedule clears up! 🙂

**Comment by BboyAkers** [comment]
Update, I'll start digging into this over the weekend!

**Comment by RoyalSix** [comment]
Hi I am wondering how can I provide the same clean experience that OpenSea has when deeplinking.

Once the user accesses `https://metamask.app.link/dapp/opensea.io` they are simply provided a connect button and then a nice connected popup at the bottom of the screen. 

Yet when I try the same procedure using a deeplink for my app. It gets redirected to the browser window on the metmask app.

**Comment by alexanderMontague** [comment]
> 

This is also something I am looking to do. Couldn't find any docs on it. Just authorize through Metamask mobile and then redirect back to the dapp with the provider initialized

**Comment by MogoHu** [comment]
> > Hi I am wondering how can I provide the same clean experience that OpenSea has when deeplinking.
> > Once the user accesses `https://metamask.app.link/dapp/opensea.io` on their mobile device they are simply provided a connect button and then a nice connected popup at the bottom of the screen.
> > Yet when I try the same procedure using a deeplink for my app. It gets redirected to the browser window on the metmask app.
> 
> This is also something I am looking to do. Couldn't find any docs on it. Just authorize through Metamask mobile and then redirect back to the dapp with the provider initialized

I would like to know if you have solved this problem, I am also working on it recently, thank you

**Comment by alexandratran** [comment]
@matheus-gsilva-ifood @RoyalSix @alexanderMontague @MogoHu Is this still an issue for any of you? [MetaMask SDK](https://docs.metamask.io/wallet/how-to/use-sdk/) should solve some issues with deeplinking.

**Comment by MogoHu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MogoHu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
