### ISSUE TITLE
Provider not found in metamask app

### ISSUE THREAD

**Issue by sakshamverenkar** [MetaMask/metamask-docs#251]
Dear team
I am using @metamask/provider to detect the provider in my webapp. Upon integration, I tested that it works fine on web (chrome extension) and iOS (metamask app). However, on android (metamask app), its not able to detect the provider. I've added alerts on the page as well to debug the same. On web, the alerts work fine. On android metamask app, it shows provider not found, please install metamask. I'm unable to understand why the same is not getting detected in android app. Please help here.

The url for  my webapp - https://fervent-pike-7afa22.netlify.app

**Comment by rohitgoyal** [comment]
+1

**Comment by BboyAkers** [comment]
Hmm interesting! I see you're actually using`@metamask/detect-provider`. Can you create an issue in that repo?

https://github.com/MetaMask/detect-provider

Very interesting issue, thanks for finding it!

**Comment by Gudahtt** [comment]
Closing, as this issue has been transferred to the aforementioned repo.
