### ISSUE TITLE
"Add Token App" returns blank page

### ISSUE THREAD

**Issue by chuacw** [MetaMask/metamask-docs#256]
From: https://docs.metamask.io/guide/registering-your-token.html#code-free-example click on "Add Token App".
The resulting page is blank, so it doesn't invoke Metamask, which is installed in my browser.

Name 	Firefox
Version 	89.0
Build ID 	20210527174632
Update Channel 	release
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
OS 	Windows_NT 10.0 17763

**Comment by BboyAkers** [comment]
Hmmm Interesting Thank you!! I see that the live demo is broken. I'll pull down the repo and look into it! 🙂 https://github.com/MetaMask/Add-Token

**Comment by BboyAkers** [comment]
Put in a PR 🙂 
https://github.com/MetaMask/Add-Token/pull/39

**Comment by BboyAkers** [comment]
Merged the PR! Closing Issue :)
