### ISSUE TITLE
Questionable word choice: "Do you have multiple wallets installed?"

### ISSUE THREAD

**Issue by lhoenig** [MetaMask/metamask-docs#259]
https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider
```solidity
function startApp(provider) {
  // If the provider returned by detectEthereumProvider is not the same as
  // window.ethereum, something is overwriting it, perhaps another wallet.
  if (provider !== window.ethereum) {
    console.error('Do you have multiple wallets installed?');
  }
  // Access the decentralized web!
}
```
I mean - why would you call it a wallet. Even in the comments. MetaMask is an Ethereum provider that includes wallet functionality of course. Somehow asking if the user has another "Wallet" installed.. it rubs me in the worst way. Maybe its just me on this specific day, I don't know.
I find it to reinforce unprofessionalism and lack of knowledge on the side of the user. Wouldn't the correct way to express that be 

**"Do you have another Ethereum [provider,client] installed?"**

Correct me if I'm wrong, but I would love to see that go from this doc page.

**Comment by BboyAkers** [comment]
1. I have a family/life and a full-time job. Anything I do here is out of genuine love and appreciation for the Ethereum ecosystem, there are many improvements I want to make within the documentation. I've been mapping them out.
2. If you have a problem create a PR. This is open source.
3. It's HIGHLY unprofessional for you to speak so rudely on a GitHub issue. Please fix your attitude.

I'm always excited to improve the documentation and work with individuals in the ecosystem, that's something I genuinely enjoy! I do not collaborate with disrespectful individuals.

Closing.

**Comment by lhoenig** [comment]
Sorry - I tried to edit the title to tone it down, but apparently that didn't work. I don't think I meant it to come across _that_ harsh. Still I think I have a point beside my failure to communicate it properly. I will try again with a PR.

**Comment by BboyAkers** [comment]
I think it shouldn't have come across harsh period. You aren't paying me. I get paid $135k+/yr and my manager, team, and VP's of Microsoft still treat me with respect. I do this for free, and out of genuine passion, like many others. Remember that next time you open an issue on ANY Open Source Repository.

**Comment by lhoenig** [comment]
Again, I'm sorry. And I won't do that mistake again. I hope you see at least I'm passionate too if I care about such details. Nothing was directed at you personally - I had no idea this repo is apparently managed by one person, let alone that person being you.
