### ISSUE TITLE
Accessing Accounts page grammar

### ISSUE THREAD

**Issue by pcowgill** [MetaMask/metamask-docs#26]
It says "but no use as as important as calling" on the [Accessing Accounts](https://metamask.github.io/metamask-docs/Main_Concepts/Accessing_Accounts) page in the docs, and that doesn't make sense. Please consider rewording this with the intended meaning. Thanks!

**Comment by BboyAkers** [comment]
Fixed: Referencing pull request https://github.com/MetaMask/metamask-docs/pull/84

**Comment by BboyAkers** [comment]
Thank you for the catch!
