### ISSUE TITLE
window.ethereum.off is not a function

### ISSUE THREAD

**Issue by Derked** [MetaMask/metamask-docs#270]
The emitter off function does not seem to be implemented for window.ethereum as an alias for removeListener. 

https://nodejs.org/api/events.html#events_emitter_off_eventname_listener

`window.ethereum.on('accountsChanged', handleAccountsChanged)`  

`window.ethereum.removeListener('accountsChanged', handleAccountsChanged)` works

`window.ethereum.off('accountsChanged', handleAccountsChanged)` returns "window.ethereum.off is not a function" 

Thanks.

**Comment by Derked** [comment]
https://github.com/MetaMask/metamask-extension/issues/10873

duplicate issue -- apologies.

**Comment by BboyAkers** [comment]
No worries! 🙂
