### ISSUE TITLE
Interact with Metamask swap router

### ISSUE THREAD

**Issue by roccomuso** [MetaMask/metamask-docs#284]
Why the router has no ABI declared?
Is there an easy way to interact with the Metamask router?

**Comment by alexandratran** [comment]
@roccomuso Can you elaborate if this is still an issue?

**Comment by roccomuso** [comment]
still an issue, do you have a public ABI for the Swap Router?

**Comment by alexandratran** [comment]
@roccomuso There's no public ABI, sorry! This is due to legal and intellectual property concerns. However, this may be revisited in the future.
