### ISSUE TITLE
About params value convertion for ethereum.request on method eth_sendTransaction

### ISSUE THREAD

**Issue by anilnabin25** [MetaMask/metamask-docs#285]
currently i am passing the static value  on the transaction parameters which is `0x16345785d8a0000` and works properly
```
const transactionParameters = {
    nonce: '1234', // ignored by MetaMask
    gasPrice: '0x3b9aca00', // customizable by user during MetaMask confirmation.
    gas: '21000', // customizable by user during MetaMask confirmation.
    // Required except during contract publications.// put you other ganache account to test
    to: '0xd6761CC3062221d07FFB68912FcCcd6FFf7427aD',
    from: selectedAddress[0], // must match user's active address.
    value: '0x16345785d8a0000', // Only required to send ether to the recipient from the initiating external account.
  };

  await ethereum.request({
    method: 'eth_sendTransaction',
    params: [transactionParameters],
  })
```
 but i want the value to be dynamic  like `1.2 eth` or `1.5 eth` or etc. 
 Please help me how to convert the  value line `1.2 eth ` to the  approprate value so that i can pass on the `transactionParameters`

**Comment by Claudio060320** [comment]
> currently i am passing the static value on the transaction parameters which is `0x16345785d8a0000` and works properly
> 
> ```
> const transactionParameters = {
>     nonce: '1234', // ignored by MetaMask
>     gasPrice: '0x3b9aca00', // customizable by user during MetaMask confirmation.
>     gas: '21000', // customizable by user during MetaMask confirmation.
>     // Required except during contract publications.// put you other ganache account to test
>     to: '0xd6761CC3062221d07FFB68912FcCcd6FFf7427aD',
>     from: selectedAddress[0], // must match user's active address.
>     value: '0x16345785d8a0000', // Only required to send ether to the recipient from the initiating external account.
>   };
> 
>   await ethereum.request({
>     method: 'eth_sendTransaction',
>     params: [transactionParameters],
>   })
> ```
> 
> but i want the value to be dynamic like `1.2 eth` or `1.5 eth` or etc. Please help me how to convert the value line `1.2 eth ` to the approprate value so that i can pass on the `transactionParameters`

**Comment by alexandratran** [comment]
@anilnabin25 Can you elaborate on your question if this is still an issue?
