### ISSUE TITLE
Owned Opensea Rinkeby NFTs report "OPS you are not the owner"

### ISSUE THREAD

**Issue by Lelegithub** [MetaMask/metamask-docs#288]
Hello, Inside my Metamask mobile wallet: 0x2606954b7193920a231eBB119f1a786687c8A3F2

I am am trying to add manually the NFTS I own on Rinkeby Network:
https://testnets.opensea.io/0x2606954b7193920a231ebb119f1a786687c8a3f2

I added manually the Contract and Toke ID but it says I am not the owner! Could you please fix this? Thanks
![image](https://user-images.githubusercontent.com/3763810/138365519-3a7de276-7870-421d-93ef-350263c0c80c.png)

**Comment by alexandratran** [comment]
@Lelegithub is this still an issue for you, or is this okay to close?
