### ISSUE TITLE
Dart support for Metamask

### ISSUE THREAD

**Issue by user2745** [MetaMask/metamask-docs#294]
I'm working with the AthleteX team to implement an 'Add AX token' button to metamask, and we're running into trouble.  

Here is the code we've written:

      eth.rawRequest('wallet_watchAsset', {
            params: {
      type: 'ERC20', 
      options: {
        address: tokenAddress, 
        symbol: tokenSymbol, 
        decimals: tokenDecimals, 
        image: tokenImage, 
      },
    },
      });

Need - looking for dart support with metamask to make this process easier.

**Comment by BboyAkers** [comment]
Hey! Sorry 😅 , i'm not familiar with DART. Does using ethereum.request instead of eth.raw? What does the base ethereum object look like in DART?

**Comment by user2745** [comment]
gotcha @BboyAkers we use this library - 
https://pub.dev/packages/web3dart


The base Ethereum object looks like normal ethereum - ref here
https://pub.dev/documentation/web3dart/latest/browser/Ethereum-class.html

P.S. please @user2745  me so I can remember to check this in a timely manner. Thank you :)

**Comment by BboyAkers** [comment]
@user2745 is there a test repo you have I can look at? I've been digging into it and looking at https://github.com/simolus3/web3dart/tree/master/example/metamask
but no avail 😅. Is there an error message you're receiving?

**Comment by user2745** [comment]
Yessir! Please checkout SportsToken page on GitHub, I will send a link

**Comment by user2745** [comment]
@BboyAkers
https://github.com/SportsToken/ax_dapp

**Comment by user2745** [comment]
@BboyAkers
https://github.com/SportsToken/ax_dapp

**Comment by BboyAkers** [comment]
Will be digging into this!

**Comment by ndevmetax** [comment]
> I'm working with the AthleteX team to implement an 'Add AX token' button to metamask, and we're running into trouble.
> 
> Here is the code we've written:
> 
> ```
>   eth.rawRequest('wallet_watchAsset', {
>         params: {
>   type: 'ERC20', 
>   options: {
>     address: tokenAddress, 
>     symbol: tokenSymbol, 
>     decimals: tokenDecimals, 
>     image: tokenImage, 
>   },
> },
>   });
> ```
> 
> Need - looking for dart support with metamask to make this process easier.


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by httpJunkie** [comment]
@BboyAkers did you get anywhere with this? LMK...

**Comment by BboyAkers** [comment]
@httpJunkie I wasn't able to figure it out unfortunately 🙁, sorry @user2745

**Comment by user2745** [comment]
hey @BboyAkers  we were able to build a solution that works.  details are in the dapp but if you're unfamiliar with BLoC architecture may be confusing.  I can include a direct link

**Comment by BboyAkers** [comment]
Please do!! @user2745
