### ISSUE TITLE
Connect to a wallet on mobile using window.ethereum and access to the Ethereum Provider API ?

### ISSUE THREAD

**Issue by romain130492** [MetaMask/metamask-docs#320]
How to connect a wallet using window.ethereum on mobile ? (iphone/android browser) any ideas how to request metamask wallet connection when using:

```
  const accounts = await ethereum.request({
            method: 'eth_requestAccounts' 
      });
```
on a mobile?

window.ethereum is always undefined. basically it doesnt get injected in the browser even when metamask is installed.so i'm wondering how we are supposing to connect a wallet on mobile

Thanks!

**Comment by ademidun** [comment]
This [answer on Reddit](https://www.reddit.com/r/Metamask/comments/rlafq5/comment/hpgeka7/?utm_source=share&utm_medium=web2x&context=3) suggests using the Metamask browser on ios or Android. Not the perfect solution since you have to install another app, but it works really well.

**Comment by BboyAkers** [comment]
@ademidun  for answering this! 🙂 Yes, you'll have to use the MetaMask mobile app due to the `window.ethereum` object not being injected into the browser. The MM Mobile app does exactly that.

**Comment by ndevmetax** [comment]
> How to connect a wallet using window.ethereum on mobile ? (iphone/android browser) any ideas how to request metamask wallet connection when using:
> 
> ```
>   const accounts = await ethereum.request({
>             method: 'eth_requestAccounts' 
>       });
> ```
> 
> on a mobile?
> 
> window.ethereum is always undefined. basically it doesnt get injected in the browser even when metamask is installed.so i'm wondering how we are supposing to connect a wallet on mobile
> 
> Thanks!

I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/
