### ISSUE TITLE
Use MetaMask in a Custom Chrome Extension

### ISSUE THREAD

**Issue by emorling** [MetaMask/metamask-docs#339]
How to use MetaMask in a Custom Chrome Extension? Adding it now simply produced "Non ethereum enabled browser"

**Comment by BboyAkers** [comment]
I'm sorry can you elaborate? Are you wanting to set it up for local development?

**Comment by BboyAkers** [comment]
Going to close, due to inactivity. Please re-open when you comment back! 🙂
