### ISSUE TITLE
Detect if the metamask is installed fail

### ISSUE THREAD

**Issue by maggiensc100** [MetaMask/metamask-docs#37]
Hi,
I use the Metamask "Quick Started" sample code to detect that,
But I always got the alert 'Looks like you need a Dapp browser to get started.' even the metamask is installed.

The Metamask info is V7.4.0 in Chrome.
Someone help me to fix that?
thank you :)

if (typeof window.ethereum === 'undefined') {
        alert('Looks like you need a Dapp browser to get started.')
        alert('Consider installing MetaMask!')

    } else {

        // In the case the user has MetaMask installed, you can easily
        // ask them to sign in and reveal their accounts:
        ethereum.enable()

            // Remember to handle the case they reject the request:
            .catch(function (reason) {
                if (reason === 'User rejected provider access') {
                    // The user didn't want to sign in!
                } else {
                    // This shouldn't happen, so you might want to log this...
                    alert('There was an issue signing you in.')
                }
            })
            // In the case they approve the log-in request, you'll receive their accounts:
            .then(function (accounts) {
                // You also should verify the user is on the correct network:
                if (ethereum.networkVersion !== desiredNetwork) {
                    alert('This application requires the main network, please switch it in your MetaMask UI.')

                    // We plan to provide an API to make this request in the near future.
                    // https://github.com/MetaMask/metamask-extension/issues/3663
                }

                // Once you have a reference to user accounts,
                // you can suggest transactions and signatures:
                const account = accounts[0]
                sendEtherFrom(account, function (err, transaction) {
                    if (err) {
                        return alert(`Sorry you weren't able to contribute!`)
                    }

                    alert('Thanks for your successful contribution!')
                })

            })
    }

**Comment by BboyAkers** [comment]
We've updated the docs but i'll go ahead and write a nice 'Getting Started' sample code to help out with a simple "Detect MetaMask" for a dapp. You can also reference https://github.com/MetaMask/metamask-docs/pull/82 it'll soon be merged and it'll show you how to create a simple connection link to detect MetaMask.

**Comment by BboyAkers** [comment]
#82  is merged. Closing this issue.
