### ISSUE TITLE
Extension Connect popup doesn't pull the right favicon

### ISSUE THREAD

**Issue by eladmeidar** [MetaMask/metamask-docs#371]
Trying to conenct a wallet using the extension, I have a valid favicon in the`<head>` section:
```html
<link ng-if="$platformManager.platform.name === 'niio'" href="img/brand/test/favicon.ico?v=2" rel="shortcut icon" type="image/x-icon" class="ng-scope">
```
and I have verified that the right favicon is showing in the browser tab and using a favicon validation tool.
when opening the extension for connecting a wallet, the favicon isn't showing:
<img width="301" alt="Screen Shot 2022-01-27 at 12 27 37" src="https://user-images.githubusercontent.com/29753/151340860-ee72ded5-1dc9-4942-a03c-748fce463a36.png">

how do we fix this?

**Comment by BboyAkers** [comment]
Hey! This seems more like it should be under the extension not the documentation! Try posting it there! 🙂 If not re-open this and I'll look further into it!
