### ISSUE TITLE
Improve snaps reference documentation

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-docs#373]
The snaps reference documentation currently lists dapp API methods and snap API methods alongside each other. It also doesn't explain which dapp API methods are available to snaps.

We should update the snaps reference documentation to better distinguish between the dapp API methods and the API available to snaps, and we should ensure the API available to snaps is described completely (including all available dapp provider methods).

## Outcome

Coverage of all Snaps API methods in the Snaps and Flask section of the new documentation site.

**Comment by ziad-saab** [comment]
It looks to me like this might be duplicated effort from #602 which @FrederikBolding has already started working on in #603
Can we please confirm if that's the case?

**Comment by Montoya** [comment]
Yes, will close this. Will open another issue if something else in the reference documentation needs updating but #602 seems to cover everything mentioned here.
