### ISSUE TITLE
Metamask deeplink integration

### ISSUE THREAD

**Issue by stefanoromanello** [MetaMask/metamask-docs#377]
Hi, I'm new to web3 and I would like to know how to implement metamask authentication in my flutter mobile project. 
I've looked at [THIS ](https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum) page and I think the deeplink is the most versatile solution but I have no idea on how to use it. Once press the button with the deeplink, the user is redirected to a browser and asked for credentials from the mobile version of metamask's app, and then what is going to happen?

**Comment by BboyAkers** [comment]
The browser in the Mobile App has the `Ethereum` object injected into it and has a means for the user to interface with their MM Wallet. Does that answer your question? As for authentication can you please elaborate on that part? 🙂

**Comment by BboyAkers** [comment]
Going to close due to inactivity! Please re-open if you have any more questions! 🙂 @stefanoromanello I would love to know more!
