### ISSUE TITLE
Wrong return value for eth_requestAccounts

### ISSUE THREAD

**Issue by andy0130tw** [MetaMask/metamask-docs#40]
The [documentation](https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider) says the method `eth_requestAccounts` returns **an array of accounts**, however it returns a **JSON-RPC response** as of MetaMask 7.4.0. Probably a bug of MetaMask.

# To reproduce

In any page containing an EthereumProvider for a browser installed MetaMask 7.4.0, evaluate the following statement:

```javascript
ethereum.send('eth_requestAccounts').then(console.log)
// {id: 1, jsonrpc: "2.0", result: ['0x1234...']}
```

**Comment by BboyAkers** [comment]
@jennypollack @danfinlay

**Comment by BboyAkers** [comment]
@andy0130tw it seems that if you do response.results, it will give you the array you're wanting. Are you expecting the array to be at the base of the response?

**Comment by andy0130tw** [comment]
Yes. I just wanted to point out a mistake of documentation and it might lead to confusion when adapting MetaMask's provider with other frameworks like web3.js. Even the examples are incorrect.
I believe the current behavior is a design choice to be EIP-1193 compliant.

**Comment by danfinlay** [comment]
Yes, this would've been a breaking change, and so there was a very recent change to EIP-1193:

- The current `send()` behavior which returns `Promise<{ results: <any> }>` will remain.
- A new method `request()` will be added, which returns the intended result `<any>`.

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md

So this is indeed a problem with he docs: @BboyAkers is correct, and we should change to match his description.

**Comment by BboyAkers** [comment]
I'll create a pull request and change it in the docs

**Comment by BboyAkers** [comment]
Pull request made! https://github.com/MetaMask/metamask-docs/pull/83
