### ISSUE TITLE
Permissions only to get user account wallet address

### ISSUE THREAD

**Issue by patnir** [MetaMask/metamask-docs#410]
Is there a way to request a permission that only allows the Dapp to know the user's address and nothing else? 

![image](https://user-images.githubusercontent.com/13268167/155057603-e3daf014-99e5-4ee1-9587-e8afcd6d3d21.png)

Normally, a site is allow to do all 3 of the above using the `eth_requestAccounts` method. Is there a way to only allow the Dapp to `see address`?

**Comment by BboyAkers** [comment]
Hey!!
```javascript
  getAccountsButton.addEventListener('click', async () => {
    //We use eth_accounts because it returns a list of addresses owned by us.
    const accounts = await ethereum.request({ method: 'eth_accounts' });
    //We take the first address in the array of addresses and display it
    getAccountsResult.innerHTML = accounts[0] || 'Not able to get accounts';
  });
```

This should work!
