### ISSUE TITLE
Convert docs to Gatsby or Next.js

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-docs#412]
Using React will let us keep our repos consistent, easy to contribute to, and makes it possible to use our MetaMask components within our docs in the future. The two most popular frameworks available to us are Next.js and Gatsby.

**Comment by rekmarks** [comment]
I think we should use Next.js since it, per the [2022 Stackoverflow survey](https://survey.stackoverflow.co/2022/#most-popular-technologies-database) has more users and is more loved than Gatsby.

**Comment by brad-decker** [comment]
Agree with the decision to use Next.js. I've used it in the past and would love to use it for our documentation efforts.

**Comment by BboyAkers** [comment]
I'll whip up a prototype in Next.js I just finished up some Next.js stuff for a friend 🙂

**Comment by shanejonas** [comment]
@BboyAkers we have it started in this repo: https://github.com/MetaMask/metamask-docs-next

**Comment by httpJunkie** [comment]
This is currently being worked on by @shanejonas @BelfordZ @GuiBibeau and @httpJunkie this is should be a longer running epic that we track in seperately.

**Comment by alexandratran** [comment]
Converted to docusaurus
