### ISSUE TITLE
Connect Metamask with a native mobile app built with Flutter

### ISSUE THREAD

**Issue by EBP20** [MetaMask/metamask-docs#415]
I want to connect the app to Metamsk to get the user account and signature from the user to confirm the transaction. But the problem is that when I enter Metamsk from the app, I am not asked any questions to confirm the connection and nothing happens inside Metamsk, it is like only the Metamsk app is opened and when I back up and return to the app, the null account is returned. this is code:

```
`_walletConnect() async {
    final connector = WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: const PeerMeta(
        name: 'WalletConnect',
        description: 'WalletConnect Developer App',
        url: 'https://walletconnect.org',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    );
    connector.on('connect', (session) => print(session));
    connector.on('session_update', (payload) => print(payload));
    connector.on('disconnect', (session) => print(session));

    if (!connector.connected) {
      session = await connector.createSession(
          chainId: 97,
          onDisplayUri: (uri) async => {print(uri), await launch(uri)});
    }

    setState(() {
      account = session.accounts[0];
      print(account);
    });

    if (account != null) {
      final client = Web3Client(rpc, Client());
      EthereumWalletConnectProvider provider =
          EthereumWalletConnectProvider(connector);
      credentials = WalletConnectEthereumCredentials(provider: provider);
      yourContract = ethUtils.getDeployedContract(myAddress, client);
    }   `
```

**Comment by hirad** [comment]
@EBP20 I'm having a similar issue. Did you ever resolve this?

**Comment by ndevmetax** [comment]
> I want to connect the app to Metamsk to get the user account and signature from the user to confirm the transaction. But the problem is that when I enter Metamsk from the app, I am not asked any questions to confirm the connection and nothing happens inside Metamsk, it is like only the Metamsk app is opened and when I back up and return to the app, the null account is returned. this is code:
> 
> ```
> `_walletConnect() async {
>     final connector = WalletConnect(
>       bridge: 'https://bridge.walletconnect.org',
>       clientMeta: const PeerMeta(
>         name: 'WalletConnect',
>         description: 'WalletConnect Developer App',
>         url: 'https://walletconnect.org',
>         icons: [
>           'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
>         ],
>       ),
>     );
>     connector.on('connect', (session) => print(session));
>     connector.on('session_update', (payload) => print(payload));
>     connector.on('disconnect', (session) => print(session));
> 
>     if (!connector.connected) {
>       session = await connector.createSession(
>           chainId: 97,
>           onDisplayUri: (uri) async => {print(uri), await launch(uri)});
>     }
> 
>     setState(() {
>       account = session.accounts[0];
>       print(account);
>     });
> 
>     if (account != null) {
>       final client = Web3Client(rpc, Client());
>       EthereumWalletConnectProvider provider =
>           EthereumWalletConnectProvider(connector);
>       credentials = WalletConnectEthereumCredentials(provider: provider);
>       yourContract = ethUtils.getDeployedContract(myAddress, client);
>     }   `
> ```


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/
