### ISSUE TITLE
add chrome error

### ISSUE THREAD

**Issue by zhangyi999** [MetaMask/metamask-docs#42]
error:
Name of a key "directdepositqitmm'erexplainer" is invalid. Only ASCII [a-z], [A-Z], [0-9] and "_" are allowed.

`chrome 78.0.3904.108 （64）`

**Comment by BboyAkers** [comment]
@zhangyi999 Is this still relevant to the new docs? If not i'd be great to close this issue!

**Comment by BboyAkers** [comment]
@zhangyi999 Any update?

**Comment by BboyAkers** [comment]
Closing due to no update. Please recreate a new issue if it is still persisting.
