### ISSUE TITLE
On disconnect event listener not working

### ISSUE THREAD

**Issue by arndom** [MetaMask/metamask-docs#423]
I attempted to use this snippet from the docs: `ethereum.on('disconnect', handler: (error: ProviderRpcError) => void);` to carry out some actions in my react app but it didn't run at all, has anyone faced a similar issues

**Comment by httpJunkie** [comment]
@arndom is this still an issue you are facing? I would need more context into your code and what you are trying to do. This snippet emits this event if MetaMask cannot submit RPC requests to any chain. Is this what you intend to detect? What are these actions you are trying to carry out? What exactly are you trying to achieve?

**Comment by arndom** [comment]
@httpJunkie I'm not facing the issue any longer...found a way around to get what I wanted, can't remember how though...been a while. I'll close the issue.
