### ISSUE TITLE
registering-function-names.md Out of date.

### ISSUE THREAD

**Issue by ilovemesomeramen** [MetaMask/metamask-docs#427]
I suspect `registering-function-names.md` is out of date, since following the steps described to register a function name still only yields `CONTRACT INTERACTION` in the MetaMask extension.

**Comment by BboyAkers** [comment]
Hmmm interesting I'll dig into this!

**Comment by httpJunkie** [comment]
@BboyAkers were you able to look into this?

**Comment by alexandratran** [comment]
The [Display method names](https://docs.metamask.io/wallet/how-to/display/method-names/) page was updated in https://github.com/MetaMask/mm-docs-v2/pull/59 to replace Parity on-chain registry with Ethereum Signature Database. See the issue addressed: https://github.com/MetaMask/mm-docs-v2/issues/21
