### ISSUE TITLE
Link to "File an issue" in documentation obfuscates last items.

### ISSUE THREAD

**Issue by kanewaltman** [MetaMask/metamask-docs#43]
The container that displays "Found a documentation bug? File an issue" obfuscates the last items. In general i've noticed that scrolling the left sidebar feels a bit wonky.
![Capture](https://user-images.githubusercontent.com/42149613/73355977-f40ecd00-42a1-11ea-9631-aa6521c7eb59.PNG)

**Comment by BboyAkers** [comment]
Hey! Is this still relevant to the new docs? If not i'd be great to close this issue 🙂

**Comment by BboyAkers** [comment]
New Docs, fixed the problem. Closing issue
