### ISSUE TITLE
How hard would it be for my project to implement metamask.

### ISSUE THREAD

**Issue by Toni-d-e-v** [MetaMask/metamask-docs#432]
We are working on a blockchain cryptocurrency that will support EVM, could we just make separate rpc api for the metamask so it could send receive coins? We use same wallet format as ethereum. What is minimum to get it working.

**Comment by BboyAkers** [comment]
Have you looked into MetaMask snaps? That could be a direction optimal for what you might need! 🙂

**Comment by httpJunkie** [comment]
Here is the RPC method you would want to use:
https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain
