### ISSUE TITLE
ethereum.removeListener not working

### ISSUE THREAD

**Issue by essserrr** [MetaMask/metamask-docs#434]
**MetaMask Version 10.11.2**
**Chrome version Version 99.0.4844.74**

Hello! I have problems with removing event listeners in Metamask. I subscribe and unsubscribe events like in the following sample code (it is almost the same as in [Metamask docs](https://docs.metamask.io/guide/ethereum-provider.html#events)): 
```
const chainChangedHandler = () => {
  console.log("Say 'Hello' when chain is changed")
}

function  subscribe() {
  window.ethereum.on("chainChanged", chainChangedHandler);
}

function  unsubscribe() {
  window.ethereum.removeListener("chainChanged", chainChangedHandler);
}

// later in my code
subscribe();
unsubscribe();
subscribe();
unsubscribe();
subscribe();
```

Expected result here is that `chainChangedHandler ` triggers only once since every `subscribe` was followed by `unsubscribe`, instead I get `console.log("Say 'Hello' when chain is changed")` 3 times (none of the listeners was removed).

**Comment by BboyAkers** [comment]
Hey! Could you post a sample project with this? I feel as though this could be solved by adding certain conditional logic or implementing a different pattern within the codebase you're in. 🙂
