### ISSUE TITLE
use wallet connect swift request personal_sign

### ISSUE THREAD

**Issue by peter-yen** [MetaMask/metamask-docs#440]
Hi,
I have a question, I'm use wallet connect swift to request the signature returned by personal_sign from metamask,
Unable to successfully verify signature in JS ethers.utils.VerifyMessage?
Thank you🙏

**Comment by BboyAkers** [comment]
I'm sorry I'd love to help! Is there a project/sample I can work with? 🙂

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by peter-yen** [comment]
I found the problem, my address is not using eip55, I can pass the verification after using it, thank you

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok
