### ISSUE TITLE
Documentation mismatch for handling events like chainChanged

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-docs#443]
At https://docs.metamask.io/guide/ethereum-provider.html#chainchanged there is TypeScript example:
````ts
ethereum.on('chainChanged', handler: (chainId: string) => void);
````

However, this doesn't work, e.g. in the following code producing an error on the `function` keyword for the event handler:

````ts
import type { MetaMaskInpageProvider } from '@metamask/providers';
declare var ethereum: MetaMaskInpageProvider; //actually found in global scope definition
const setReloadOnChainChange = function() {
	if (typeof ethereum !== 'undefined' && ethereum.isMetaMask) {
		ethereum.on('chainChanged', function (_chainId: string) {
				console.log('New chainID:', _chainId); //or other code actually using this value
				window.location.reload();
		});
	}
};
````
The error is:
>Argument of type '(_chainId: string) => void' is not assignable to parameter of type '(...args: unknown[]) => void'.
  Types of parameters '_chainId' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'string'.ts(2345)

In trying to find how other TypeScript projects got this to work, I found [all](https://github.com/Uniswap/interface/blob/9e2dc9a4357e5820aa967a3da5023032ed0cb50f/src/hooks/web3.ts#L74) [of](https://github.com/mooni/mooni/blob/0a30d9e80fe91fcb689e804c1ffa4d28ab148c50/app/src/lib/eth.ts#L58) [these](https://github.com/InjectiveLabs/injective-ts/blob/ffcd1add9962cb127347e3f991d6cb9e01ea2428/packages/web3-strategy/src/strategies/Metamask.ts#L173) which ignore the parameter and therefore don't have a type conflict.  [Casting](https://github.com/0xProject/website/blob/f47674cbc0e8949fcc8a91dee8b102b6409d3f12/ts/hooks/use_web3.ts#L36) [to](https://github.com/vmware-samples/vmware-blockchain-samples/blob/c0f4cc05d7da2fd819a18ef4e99028a9886c896b/artemis/clarity/src/app/main/ethereum.service.ts#L6) [any](https://github.com/zer0-os/zNS-dapp/blob/34fc4c22639d9a967c7d5f9c2a8b7be9ae5cefff/src/lib/hooks/provider-hooks.ts#L62) [is](https://github.com/darwinia-network/webkit/blob/a23c31a5a59fe29699fc844c0adf466603f2fe63/packages/utils/global.d.ts#L10) [also](https://github.com/primitivefinance/v1-interface/blob/f682d84e0d59bf9a3ee18600abb4ea6ef54ad484/src/hooks/user/index.ts#L20) [used](https://github.com/ethereum/staking-launchpad/blob/b789680e9bd96853542042a1f88d8c954153cb11/src/pages/ConnectWallet/web3Utils.ts#L94) as a strategy, sometimes even with a [note](https://github.com/freeatnet/web3-react-simple-app/blob/6d843157593c47ccd56a09f83c7f1812fd5849c2/src/features/web3/hooks.ts#L38) to fix typing.
[Writing](https://github.com/energywebfoundation/origin/blob/051544dd0ae36dee02db4924829d82c46ec3712e/packages/ui/libs/ui/web3/src/adapters/metamask/types.ts#L18) new [definitions](https://github.com/TBouder/web3-react-fork/blob/c25087d426716444010e4b08923b2c4dac259e05/packages/injected-connector/src/declarations.ts) seems reasonably popular too. 

Better documentation about how to use appropriate typing for the provider, and/or library typing that matches the documentation, would be helpful.

Note: I would also expect this provider to be assignable to the AbstractProvider type definition found in web3-core, but it is not.

**Comment by vandan** [comment]
Please find the latest docs here: https://docs.metamask.io/wallet/reference/provider-api/#chainchanged

**Comment by wbt** [comment]
I appreciate that the links changed, but the example at that link is still the same.  Was there any change to types?
