### ISSUE TITLE
event "accountsChanged" value not in right case

### ISSUE THREAD

**Issue by Jlomaka** [MetaMask/metamask-docs#446]
I have two wallets with this id (example):
-`0x98Ffg983`
-`0x98aA345bB`

When I log in under the first wallet, everything goes well, during authorization it returns the format `0x98Ffg983`, but as soon as I connect the accountsChanged event when I switch the account, I receive not `0x98aA345bB`, but for some reason `0x98aa345bb` not in right case

**Comment by Jlomaka** [comment]
If you have the same problem you can use this temporary solution to fix this problem.
```js
ethereum.on("accountsChanged", async (newAccounts: string) => {
  // newAccounts from the event don't use! incorrect wallets name
  const accounts = await web3.eth.getAccounts();
  await handleAccountChange(accounts[0] || "");
});
```

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok
