### ISSUE TITLE
Switch from `master` to `main` broke "Edit this page" links

### ISSUE THREAD

**Issue by katelynsills** [MetaMask/metamask-docs#453]
For instance, the link at the bottom of https://docs.metamask.io/guide/signing-data.html is https://github.com/MetaMask/metamask-docs/edit/master/docs/guide/signing-data.md which gives a 404. 

I believe editing [`config.js`](https://github.com/MetaMask/metamask-docs/blob/d573f5c04c5e86c750d0397b97386a50ae662b1d/docs/.vuepress/config.js#L55) to add the setting `docsBranch: 'main',` should fix it!

Here's the [relevant VuePress documentation](https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links)

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Ok

**Comment by FrederikBolding** [comment]
Thanks for reporting!
