### ISSUE TITLE
[urgent bug]Cannot change logo dapp

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-docs#489]
`When your site makes a login request to a MetaMask user, MetaMask may render a modal that display's your site icon.

We retrieve this icon using the HTML selector <head> link[rel="shortcut icon"], so to customize this icon for your site, just make sure to follow the [favicon standard](https://en.wikipedia.org/wiki/Favicon), and make sure to have a link tag within your site's head with rel = "shortcut icon", like this.

The tag's href attribute will be used for assigning the site icon.

<head>
  <link rel="shortcut icon" href="https://your-site.com/your-icon.png" />
</head>`

I cannot change the favicon, 
It only works the first time.

**Comment by httpJunkie** [comment]
Are you still having issues with this? I have had this working in the past and I'm wondering if this is still an issue.
