### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by LuozhuZhang** [MetaMask/metamask-docs#497]
About signature

This [repo Link](https://github.com/danfinlay/js-eth-personal-sign-examples) should be replaced to [test-Dapp](https://github.com/MetaMask/test-dapp)

The first repo is deprecated

**Comment by LuozhuZhang** [comment]
Doc：https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask

**Comment by BboyAkers** [comment]
Thanks for catching this! 🙂 I'll put up a PR!

**Comment by BboyAkers** [comment]
PR is up 🙂 https://github.com/MetaMask/metamask-docs/pull/513

**Comment by BboyAkers** [comment]
Fixed and merged! 🙂
