### ISSUE TITLE
Document best practices for connecting to a snap

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-docs#517]
We should document best practices for connecting a snap, especially a particular version of a snap. This should mostly come down to using `wallet_requestSnaps`.

Define a list of best practices and document them. Start with the template monorepo.

## Outcome 

Documentation is updated with one approach for connecting.

**Comment by Montoya** [comment]
Finally done! https://docs.metamask.io/snaps/how-to/work-with-existing-snaps/
