### ISSUE TITLE
Onboarding API using React has no way to define forwarderOrigin

### ISSUE THREAD

**Issue by alienking-sol** [MetaMask/metamask-docs#519]
Looking specifically at [this section](https://docs.metamask.io/guide/onboarding-library.html#using-react) in the docs. After some digging I am seeing no way to define what the forwarderOrigin URL is in order for the API to send the user _back_ to the dapp after install Metamask. 

I am seeing this possibility in [this repo using typescript](https://github.com/MetaMask/metamask-onboarding/blob/546d3193e5ec15e8c3b626f8d55f9fa0075881f3/src/index.ts#L39), but I am not using typescript. 

I would suspect that this would need to be defined within the startOnboarding function here:
```
  const onClick = () => {
    if (MetaMaskOnboarding.isMetaMaskInstalled()) {
      window.ethereum
        .request({ method: 'eth_requestAccounts' })
        .then((newAccounts) => setAccounts(newAccounts));
    } else {
      onboarding.current.startOnboarding();
    }
  };
```
but perhaps I'm missing something. Any guidance here would be appreciated.

**Comment by httpJunkie** [comment]
@shanejonas can you confirm if the docs are missing something to make the JS part of the code for the React implementation? I think you pointed this out to me before.

**Comment by alexandratran** [comment]
The SDK should be used instead of the onboarding library.
