### ISSUE TITLE
Remove metamask.wtf from domain warning list.

### ISSUE THREAD

**Issue by metamonk** [MetaMask/metamask-docs#532]
Hi I am the owner of this domain. Please remove the following domains from your block list:

https://www.metamonk.xyz/
https://metamonk.xyz/

Thank you,
metamonk

**Comment by ndevmetax** [comment]
> Hi I am the owner of this domain. Please remove the following domains from your block list:
> 
> https://www.metamonk.xyz/ https://metamonk.xyz/
> 
> Thank you, metamonk


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by BboyAkers** [comment]
Hey file an issue here please 🙂.
https://github.com/MetaMask/eth-phishing-detect
