### ISSUE TITLE
Payment with usdt

### ISSUE THREAD

**Issue by namqh** [MetaMask/metamask-docs#542]
Hello,
How to enable payment method metamask with usdt thank
![image](https://user-images.githubusercontent.com/108966388/188677370-405e2fcf-f031-41fb-a311-b7a52fccd04d.png)
Thank for help

**Comment by httpJunkie** [comment]
You cannot pay with anything but ETH, if you want to SEND USDT tokens you can ADD TOKEN which is in the UI

<img width="354" alt="Screen Shot 2022-10-13 at 12 11 36 PM" src="https://user-images.githubusercontent.com/4899480/195657320-7fa976f6-8633-4c6c-ae2e-28f43873ff82.png">
