### ISSUE TITLE
Update NodeJS link on Ethereum Provider > Events

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-docs#565]
Update link on [Events](https://docs.metamask.io/guide/ethereum-provider.html#events) to point to [Node Version 9.x](https://nodejs.org/docs/latest-v9.x/api/events.html)

**Comment by alexandratran** [comment]
@httpJunkie Is this still applicable? The [current docs](https://docs.metamask.io/wallet/reference/provider-api#events) point to https://nodejs.org/api/events.html, which is the latest Node version docs.
