### ISSUE TITLE
Rinkeby Testnet Deprecated

### ISSUE THREAD

**Issue by uday03meh** [MetaMask/metamask-docs#572]
Hi, I was going through the **Registering your Contract's Method Names** section in **Best Practices** and there is a need of a correction in this page as RInkeby network is now deprecated.

[Link to page](https://docs.metamask.io/guide/registering-function-names.html#verify)

![image](https://user-images.githubusercontent.com/59679281/199561953-90077d96-8006-43bd-a120-7ead20c8c9c2.png)

**Comment by alexandratran** [comment]
All references to deprecated testnets have been removed in the [new docs](https://docs.metamask.io/wallet/).
