### ISSUE TITLE
Is there a way to get the collectibles under the wallet？

### ISSUE THREAD

**Issue by liuyang0623** [MetaMask/metamask-docs#573]
Is there a way to get the collectibles information under the wallet, there is a display of collectibles on the metamask app on the mobile phone

**Comment by alexandratran** [comment]
Currently, if users have [NFT auto-detection](https://support.metamask.io/hc/en-us/articles/360058238591-NFT-tokens-in-your-MetaMask-wallet) enabled, MetaMask automatically displays their NFTs. A new feature is coming soon that enables dapp developers to explicitly prompt users to add their NFTs to MetaMask.
