### ISSUE TITLE
Document `fetch()` CORS issue in Snaps

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-docs#579]
CORS issues when using `fetch()` in Snaps are non-obvious. We should document that they happen and how to debug them.

**AC**

Documentation has been updated.

**Comment by Montoya** [comment]
I can provide an example of this

**Comment by ziad-saab** [comment]
@Montoya please do

**Comment by Montoya** [comment]
Here it is @ziad-saab https://github.com/MetaMask/snaps-monorepo/discussions/675#discussioncomment-3900367

**Comment by Montoya** [comment]
As of yet there seems to be no section in the docs for documenting common problems or caveats so this would include finding a place for this information in the docs.

**Comment by alexandratran** [comment]
@Montoya Can we document in the [Troubleshoot](https://docs.metamask.io/snaps/how-to/troubleshoot) page or add a note in the relevant topic page/section?

**Comment by Montoya** [comment]
We can add a note at the end of the section for endowment:network-access 

https://docs.metamask.io/snaps/reference/permissions#endowmentnetwork-access

**Comment by ziad-saab** [comment]
Related to #742. This new documentation should link to the example we create for #742
