### ISSUE TITLE
Document how to debug snaps

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/metamask-docs#580]
How to debug an extension, let alone third-party JavaScript being `eval`:ed inside in iframe in the background script of an extension, is not obvious. We should document how to debug snaps.

## Outcome

The documentation is updated with sufficient steps to find the console log in Flask. How to turn on developer mode and inspect background.html, etc.

**Comment by ziad-saab** [comment]
@Montoya looks like this is already documented here >> https://docs.metamask.io/snaps/how-to/debug-a-snap/

Are there any things that need to be changed or added?

**Comment by Montoya** [comment]
Oh wow you are right. We are good to go. Closing!
