### ISSUE TITLE
Snaps: Improve documentation for private key entropy

### ISSUE THREAD

**Issue by ritave** [MetaMask/metamask-docs#583]
A recurring criticism of our documentation was that explanation of derivation paths and entropy access is confusing.

Additionally we should also specify which derivation path MetaMask uses, because people were wondering which one we do use. Is it the legacy one (MyCrypto) or the new one, or another 

All the technical work has been done.

**AC**

Documentation has been updated.

**Comment by ziad-saab** [comment]
@ritave I've reviewed the documentation we are providing for private key management RPC functions, and it looks like all these questions are answered in there. We completely specify the derivation path in the documentation. Can you please add some guidelines on what is missing or confusing?

**Comment by ritave** [comment]
@ziad-saab 

All the correct keywords are there - "Bip-32", "Bip-44", "Slip-10" and so on, but without real explanations of what those are what and what can they do. In current state the documentation around private keys is directed towards highly experienced engineers with a lot of previous knowledge.

The question is "I'm new, I have some cool ideas, I want to get access to private keys, how do I do that", and the response "You can get BIP-32 entropy using this RPC method", while technically correct is not helpful as a starting point into learning about private key management nor is it findable at a glance.

The second question is "I want to get private keys for specifically MetaMask accounts visible in the UI, which path is it?", and I tried to find the answer right now and it took me 10 minutes of googling before I ended up on this, unofficial, list - https://gist.github.com/miguelmota/034c81886bd23b25c64ec5eda9251641

While that information can be found somewhere deep in MetaMask support pages, it should be close by snaps private key management so that people building snaps can easily get answer to that question
