### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'negative')

### ISSUE THREAD

**Issue by ktakahama** [MetaMask/metamask-docs#592]
Hello, 
I am using metamask sdk with nextjs (typescript) 
and facing the problem below. 
Please tell me how to resolve this problem.
Thank you for your support in advance.

■ Environment
- code: Typescript with Nextjs(v12), react(v18)
- pkg: "@metamask/sdk": "^0.0.1-beta.5",

■Problem
When we use metamask sdk and build nextjs project,
The front UI collapses (CSS is not applied) and button doesn't working.
※error message below

■error message (browser console)
<details><summary>expand</summary>

```
main-d31983000c640778.js:1 
TypeError: Cannot set properties of undefined (setting 'negative')
    at i (_app-e0f580f1a239ba7a.js:1670:162830)
    at _app-e0f580f1a239ba7a.js:1670:486483
    at t (_app-e0f580f1a239ba7a.js:1670:487221)
    at 94145 (_app-e0f580f1a239ba7a.js:1679:317890)
    at d (webpack-ab7ededcb24a6130.js:1:167)
    at 90523 (_app-e0f580f1a239ba7a.js:3973:7407)
    at d (webpack-ab7ededcb24a6130.js:1:167)
    at 91868 (_app-e0f580f1a239ba7a.js:3973:7212)
    at d (webpack-ab7ededcb24a6130.js:1:167)
    at 87297 (_app-e0f580f1a239ba7a.js:1679:562496)
Y @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
s @ main-d31983000c640778.js:1
c._invoke @ main-d31983000c640778.js:1
e.<computed> @ main-d31983000c640778.js:1
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
ec @ main-d31983000c640778.js:1
eu @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
s @ main-d31983000c640778.js:1
c._invoke @ main-d31983000c640778.js:1
e.<computed> @ main-d31983000c640778.js:1
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
es @ main-d31983000c640778.js:1
t.hydrate @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
Promise.then (async)
94609 @ main-d31983000c640778.js:1
d @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
d.O @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
c @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1



main-d31983000c640778.js:1 
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Y @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
s @ main-d31983000c640778.js:1
c._invoke @ main-d31983000c640778.js:1
e.<computed> @ main-d31983000c640778.js:1
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
ec @ main-d31983000c640778.js:1
eu @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
s @ main-d31983000c640778.js:1
c._invoke @ main-d31983000c640778.js:1
e.<computed> @ main-d31983000c640778.js:1
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
es @ main-d31983000c640778.js:1
t.hydrate @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
Promise.then (async)
94609 @ main-d31983000c640778.js:1
d @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
d.O @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
c @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1



main-d31983000c640778.js:1 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getInitialProps')
    at main-d31983000c640778.js:1:88100
    at s (main-d31983000c640778.js:1:103105)
    at c._invoke (main-d31983000c640778.js:1:102885)
    at e.<computed> [as next] (main-d31983000c640778.js:1:103508)
    at r (main-d31983000c640778.js:1:137)
    at u (main-d31983000c640778.js:1:336)
    at main-d31983000c640778.js:1:395
    at new Promise (<anonymous>)
    at Object.<anonymous> (main-d31983000c640778.js:1:277)
    at Object.g (main-d31983000c640778.js:1:88658)
(anonymous) @ main-d31983000c640778.js:1
s @ main-d31983000c640778.js:1
c._invoke @ main-d31983000c640778.js:1
e.<computed> @ main-d31983000c640778.js:1
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
g @ main-d31983000c640778.js:1
y @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
ec @ main-d31983000c640778.js:1
eu @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
s @ main-d31983000c640778.js:1
c._invoke @ main-d31983000c640778.js:1
e.<computed> @ main-d31983000c640778.js:1
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
Promise.then (async)
r @ main-d31983000c640778.js:1
u @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
es @ main-d31983000c640778.js:1
t.hydrate @ main-d31983000c640778.js:1
(anonymous) @ main-d31983000c640778.js:1
Promise.then (async)
94609 @ main-d31983000c640778.js:1
d @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
d.O @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
c @ webpack-ab7ededcb24a6130.js:1
(anonymous) @ main-d31983000c640778.js:1
```
</details>

■environment detail
<details><summary>expand</summary>

```
{
  "name": "web-user-nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "check-types": "tsc --noEmit",
    "lint": "next lint --fix",
    "prepare": "husky install",
    "path": "pathpida --enableStatic  -o ./src/utils/pathpida",
    "codegen": "graphql-codegen --require dotenv/config --config src/utils/apollo/codegen.js dotenv_config_path=.env.local"
  },
  "dependencies": {
    "@apollo/client": "^3.7.0",
    "@date-io/date-fns": "^1.3.13",
    "@date-io/dayjs": "^1.3.13",
    "@date-io/moment": "^1.3.13",
    "@emotion/react": "^11.10.4",
    "@emotion/server": "^11.10.0",
    "@emotion/styled": "^11.10.4",
    "@hookform/resolvers": "^2.9.8",
    "@material-ui/core": "^4.12.4",
    "@material-ui/pickers": "^3.3.10",
    "@metamask/sdk": "^0.0.1-beta.5",
    "@mui/icons-material": "^5.10.6",
    "@mui/lab": "^5.0.0-alpha.102",
    "@mui/material": "^5.10.5",
    "@mui/x-data-grid": "^5.17.5",
    "@mui/x-data-grid-pro": "^5.17.8",
    "@mui/x-date-pickers": "^5.0.2",
    "@sendgrid/mail": "^7.7.0",
    "@walletconnect/client": "^1.8.0",
    "axios": "^1.1.3",
    "babel-plugin-styled-components": "^2.0.7",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.29.3",
    "dayjs": "^1.11.5",
    "deepmerge": "^4.2.2",
    "firebase": "^9.10.0",
    "graphql": "^16.6.0",
    "i18next": "^22.0.2",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.37",
    "nanoid": "^4.0.0",
    "next": "^12.3.1",
    "next-i18next": "^12.1.0",
    "next-seo": "^5.6.0",
    "react": "^18.2.0",
    "react-device-detect": "^2.2.2",
    "react-dom": "^18.2.0",
    "react-dropzone": "^14.2.2",
    "react-hook-form": "^7.36.1",
    "react-hot-toast": "^2.4.0",
    "react-i18next": "^12.0.0",
    "react-router-dom": "^6.4.1",
    "react-share": "^4.4.1",
    "recoil": "^0.7.5",
    "recoil-persist": "^4.2.0",
    "twitter-api-v2": "^1.12.8",
    "walletconnect": "^1.7.8",
    "web3": "^1.8.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^2.13.2",
    "@graphql-codegen/typescript": "^2.7.3",
    "@graphql-codegen/typescript-operations": "^2.5.3",
    "@graphql-codegen/typescript-react-apollo": "^3.3.3",
    "@types/crypto-js": "^4.1.1",
    "@types/lodash.isequal": "^4.5.5",
    "@types/node": "18.7.23",
    "@types/react": "18.0.21",
    "@types/react-dom": "18.0.6",
    "@typescript-eslint/eslint-plugin": "^5.39.0",
    "babel-plugin-inline-react-svg": "^2.0.1",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "8.24.0",
    "eslint-config-next": "12.3.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "husky": "^8.0.1",
    "next-intercept-stdout": "^1.0.1",
    "npm-run-all": "^4.1.5",
    "pathpida": "^0.18.1",
    "prettier": "^2.7.1",
    "typescript": "4.8.3"
  }
}
```

**Comment by SUPPORTTEAMHERR** [comment]
> Hello, 
> I am using metamask sdk with nextjs (typescript) 
> and facing the problem below. 
> Please tell me how to resolve this problem.
> Thank you for your support in advance.
> 
> ■ Environment
> - code: Typescript with Nextjs(v12), react(v18)
> - pkg: "@metamask/sdk": "^0.0.1-beta.5",
> 
> ■Problem
> When we use metamask sdk and build nextjs project,
> The front UI collapses (CSS is not applied) and button doesn't working.
> ※error message below
> 
> ■error message (browser console)
> <details><summary>expand</summary>
> 
> ```
> main-d31983000c640778.js:1 
> TypeError: Cannot set properties of undefined (setting 'negative')
>     at i (_app-e0f580f1a239ba7a.js:1670:162830)
>     at _app-e0f580f1a239ba7a.js:1670:486483
>     at t (_app-e0f580f1a239ba7a.js:1670:487221)
>     at 94145 (_app-e0f580f1a239ba7a.js:1679:317890)
>     at d (webpack-ab7ededcb24a6130.js:1:167)
>     at 90523 (_app-e0f580f1a239ba7a.js:3973:7407)
>     at d (webpack-ab7ededcb24a6130.js:1:167)
>     at 91868 (_app-e0f580f1a239ba7a.js:3973:7212)
>     at d (webpack-ab7ededcb24a6130.js:1:167)
>     at 87297 (_app-e0f580f1a239ba7a.js:1679:562496)
> Y @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> s @ main-d31983000c640778.js:1
> c._invoke @ main-d31983000c640778.js:1
> e.<computed> @ main-d31983000c640778.js:1
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> ec @ main-d31983000c640778.js:1
> eu @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> s @ main-d31983000c640778.js:1
> c._invoke @ main-d31983000c640778.js:1
> e.<computed> @ main-d31983000c640778.js:1
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> es @ main-d31983000c640778.js:1
> t.hydrate @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> Promise.then (async)
> 94609 @ main-d31983000c640778.js:1
> d @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> d.O @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> c @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> 
> 
> 
> main-d31983000c640778.js:1 
> A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
> Y @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> s @ main-d31983000c640778.js:1
> c._invoke @ main-d31983000c640778.js:1
> e.<computed> @ main-d31983000c640778.js:1
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> ec @ main-d31983000c640778.js:1
> eu @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> s @ main-d31983000c640778.js:1
> c._invoke @ main-d31983000c640778.js:1
> e.<computed> @ main-d31983000c640778.js:1
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> es @ main-d31983000c640778.js:1
> t.hydrate @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> Promise.then (async)
> 94609 @ main-d31983000c640778.js:1
> d @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> d.O @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> c @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> 
> 
> 
> main-d31983000c640778.js:1 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getInitialProps')
>     at main-d31983000c640778.js:1:88100
>     at s (main-d31983000c640778.js:1:103105)
>     at c._invoke (main-d31983000c640778.js:1:102885)
>     at e.<computed> [as next] (main-d31983000c640778.js:1:103508)
>     at r (main-d31983000c640778.js:1:137)
>     at u (main-d31983000c640778.js:1:336)
>     at main-d31983000c640778.js:1:395
>     at new Promise (<anonymous>)
>     at Object.<anonymous> (main-d31983000c640778.js:1:277)
>     at Object.g (main-d31983000c640778.js:1:88658)
> (anonymous) @ main-d31983000c640778.js:1
> s @ main-d31983000c640778.js:1
> c._invoke @ main-d31983000c640778.js:1
> e.<computed> @ main-d31983000c640778.js:1
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> g @ main-d31983000c640778.js:1
> y @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> ec @ main-d31983000c640778.js:1
> eu @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> s @ main-d31983000c640778.js:1
> c._invoke @ main-d31983000c640778.js:1
> e.<computed> @ main-d31983000c640778.js:1
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> Promise.then (async)
> r @ main-d31983000c640778.js:1
> u @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> es @ main-d31983000c640778.js:1
> t.hydrate @ main-d31983000c640778.js:1
> (anonymous) @ main-d31983000c640778.js:1
> Promise.then (async)
> 94609 @ main-d31983000c640778.js:1
> d @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> d.O @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> c @ webpack-ab7ededcb24a6130.js:1
> (anonymous) @ main-d31983000c640778.js:1
> ```
> </details>
> 
> ■environment detail
> <details><summary>expand</summary>
> 
> ```
> {
>   "name": "web-user-nextjs",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "check-types": "tsc --noEmit",
>     "lint": "next lint --fix",
>     "prepare": "husky install",
>     "path": "pathpida --enableStatic  -o ./src/utils/pathpida",
>     "codegen": "graphql-codegen --require dotenv/config --config src/utils/apollo/codegen.js dotenv_config_path=.env.local"
>   },
>   "dependencies": {
>     "@apollo/client": "^3.7.0",
>     "@date-io/date-fns": "^1.3.13",
>     "@date-io/dayjs": "^1.3.13",
>     "@date-io/moment": "^1.3.13",
>     "@emotion/react": "^11.10.4",
>     "@emotion/server": "^11.10.0",
>     "@emotion/styled": "^11.10.4",
>     "@hookform/resolvers": "^2.9.8",
>     "@material-ui/core": "^4.12.4",
>     "@material-ui/pickers": "^3.3.10",
>     "@metamask/sdk": "^0.0.1-beta.5",
>     "@mui/icons-material": "^5.10.6",
>     "@mui/lab": "^5.0.0-alpha.102",
>     "@mui/material": "^5.10.5",
>     "@mui/x-data-grid": "^5.17.5",
>     "@mui/x-data-grid-pro": "^5.17.8",
>     "@mui/x-date-pickers": "^5.0.2",
>     "@sendgrid/mail": "^7.7.0",
>     "@walletconnect/client": "^1.8.0",
>     "axios": "^1.1.3",
>     "babel-plugin-styled-components": "^2.0.7",
>     "crypto-js": "^4.1.1",
>     "date-fns": "^2.29.3",
>     "dayjs": "^1.11.5",
>     "deepmerge": "^4.2.2",
>     "firebase": "^9.10.0",
>     "graphql": "^16.6.0",
>     "i18next": "^22.0.2",
>     "lodash.isequal": "^4.5.0",
>     "moment": "^2.29.4",
>     "moment-timezone": "^0.5.37",
>     "nanoid": "^4.0.0",
>     "next": "^12.3.1",
>     "next-i18next": "^12.1.0",
>     "next-seo": "^5.6.0",
>     "react": "^18.2.0",
>     "react-device-detect": "^2.2.2",
>     "react-dom": "^18.2.0",
>     "react-dropzone": "^14.2.2",
>     "react-hook-form": "^7.36.1",
>     "react-hot-toast": "^2.4.0",
>     "react-i18next": "^12.0.0",
>     "react-router-dom": "^6.4.1",
>     "react-share": "^4.4.1",
>     "recoil": "^0.7.5",
>     "recoil-persist": "^4.2.0",
>     "twitter-api-v2": "^1.12.8",
>     "walletconnect": "^1.7.8",
>     "web3": "^1.8.0",
>     "yup": "^0.32.11"
>   },
>   "devDependencies": {
>     "@graphql-codegen/cli": "^2.13.2",
>     "@graphql-codegen/typescript": "^2.7.3",
>     "@graphql-codegen/typescript-operations": "^2.5.3",
>     "@graphql-codegen/typescript-react-apollo": "^3.3.3",
>     "@types/crypto-js": "^4.1.1",
>     "@types/lodash.isequal": "^4.5.5",
>     "@types/node": "18.7.23",
>     "@types/react": "18.0.21",
>     "@types/react-dom": "18.0.6",
>     "@typescript-eslint/eslint-plugin": "^5.39.0",
>     "babel-plugin-inline-react-svg": "^2.0.1",
>     "babel-plugin-module-resolver": "^4.1.0",
>     "eslint": "8.24.0",
>     "eslint-config-next": "12.3.1",
>     "eslint-config-prettier": "^8.5.0",
>     "eslint-plugin-simple-import-sort": "^8.0.0",
>     "husky": "^8.0.1",
>     "next-intercept-stdout": "^1.0.1",
>     "npm-run-all": "^4.1.5",
>     "pathpida": "^0.18.1",
>     "prettier": "^2.7.1",
>     "typescript": "4.8.3"
>   }
> }
> ```
> 
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
