### ISSUE TITLE
Document patching used in the transaction simulation snap

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#606]
In our section on patching dependencies: 

https://docs.metamask.io/guide/snaps-patching-dependencies.html

We should go ahead and document the patching of ganache that was done in this snap: 

https://github.com/Montoya/tx-simulation-with-ganache-snap

Please check with @FrederikBolding if you need more information on how this was done

**Comment by alexandratran** [comment]
@Montoya Can we close this issue since we can no longer refer to the sunset Truffle Suite products in the docs?

**Comment by Montoya** [comment]
@alexandratran Yes
