### ISSUE TITLE
Investigate vue components for live coding examples(REPL)

### ISSUE THREAD

**Issue by BboyAkers** [MetaMask/metamask-docs#61]
Look into creating live coding examples for Ethereum methods. Interactive docs with more code examples. Make the docs more interactive by creating reactivity and real-time feedback when typing

**Comment by BboyAkers** [comment]
@jennypollack Wanting to create codesandbox.com or codepen.io examples and append them to the docs. Your thoughts?

**Comment by jennypollack** [comment]
ya i think either of these would be great!
