### ISSUE TITLE
support WalletConnect v2?

### ISSUE THREAD

**Issue by kecson** [MetaMask/metamask-docs#635]
Wallet Connect v1 is will end of support.
Do you have any plan support Wallet Connect v2?

https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

**Comment by andreahaku** [comment]
Hi @kecson https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595
