### ISSUE TITLE
MetaMask: MetaMaskUnity initialization failed

### ISSUE THREAD

**Issue by psychoduckos** [MetaMask/metamask-docs#637]
![image](https://user-images.githubusercontent.com/111517975/211502803-7afe3886-cd75-4aa1-9891-275c033d183c.png)

Good day! I tried to run a test scene in your sdk unit, but here are the errors I get. I did everything according to the official video on YouTube. Help solve the problem please

**Comment by Walletsuppport** [comment]
> ![image](https://user-images.githubusercontent.com/111517975/211502803-7afe3886-cd75-4aa1-9891-275c033d183c.png)
> 
> Good day! I tried to run a test scene in your sdk unit, but here are the errors I get. I did everything according to the official video on YouTube. Help solve the problem please
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Walletsuppport** [comment]
> ![image](https://user-images.githubusercontent.com/111517975/211502803-7afe3886-cd75-4aa1-9891-275c033d183c.png)
> 
> Good day! I tried to run a test scene in your sdk unit, but here are the errors I get. I did everything according to the official video on YouTube. Help solve the problem please
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by funnyData** [comment]
Same question with you, have you found the solution?

**Comment by andreahaku** [comment]
@psychoduckos @funnyData which version of Unity are you running? Did you get it from the Unity Assets store? Did you install the package through the tools menu?

**Comment by hairove** [comment]
I'm running into this issue as well, I'm using Mac 2017 Intel with Unity version is 2021.3.18f1.
Tried both the 1.0.0 and the new 1.1.0 version which is supposed to fix this issue on Mac Intel but somehow it does not make any different.

**Comment by cy-koichi-nishino** [comment]
We have confirmed that this bug occurs under the following conditions.
It happens with X86-64 Unity Editor on Intel Mac.
It happens in X86-64 Unity Editor on Apple Silicon(M1) Mac.
It doesn't happen in ARM64 Unity Editor on Apple Silicon(M1) Mac.
Not tested on M2 Mac.
Is this a hint to solve the problem?

**Comment by KBryan** [comment]
I was able to get this to work on Mac. Although, for me. I had to open the ecies file that is provided with the SDK. I opened the iOS version as I'm more geared towards mobile development. This may be your issue as well. So, basically right-clicking on the file and selecting open fixed my issue. Not, you will get similar results. It is worth a try.

![Uploading mac_ecies.png…]()
