### ISSUE TITLE
The documentation should explain the difference between the site versus the snap package.

### ISSUE THREAD

**Issue by ritave** [MetaMask/metamask-docs#643]
Context https://github.com/MetaMask/snaps-monorepo/discussions/1129#discussioncomment-4699748

One pain point that repeatedly occurs is that developers are confused about the relation between the NPM package for the website (React/Angular/etc), and the snap package.

Documentation clearing up the distinction might help

**Comment by Montoya** [comment]
We need documentation about the template, which would include this. Should this documentation be on our docs site or in the README of the template? I am thinking it would be on the docs site because we are going to teach developers to use the CLI rather than going to the template on GitHub.

**Comment by Montoya** [comment]
Fixed here https://github.com/MetaMask/metamask-docs/pull/897
