### ISSUE TITLE
Remove "Recent Breaking Provider Changes"

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#650]
From the [docs homepage](https://docs.metamask.io/guide/) and [provider API reference](https://docs.metamask.io/guide/ethereum-provider.html):

> Recent Breaking Provider Changes
> If you are an Ethereum application developer and are looking for information about our January 2021 provider API changes, please see our [Migration Guide](https://docs.metamask.io/guide/provider-migration.html) for more details.

January 2021 is no longer "recent" so these warnings should probably be removed/updated.

**Comment by daredevil3435** [comment]
is this issue still open? if yes I want to start working

**Comment by alexandratran** [comment]
Hi @daredevil3435, we've recently launched our new doc site, and the new repo is currently at https://github.com/MetaMask/mm-docs-v2. So issues in this repo are no longer applicable.

**Comment by daredevil3435** [comment]
oh!! okay okay
