### ISSUE TITLE
MetaMask SDK not working with Browser Extension detect

### ISSUE THREAD

**Issue by migbash** [MetaMask/metamask-docs#665]
I have tried to use the following example => https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-js/metamask-sdk-pure-javascript.html

And when using with the `mobile` device, all works well - opens and redirects back to the browser. However, on the desktop the `extension` is not detected, and the `Install the Extension` always shows up.

Is this meant to be always like this? I have noticed that on the `https://recordit.co/g9u0X2S60Z` example of `Desktop` recording the `Browser Extension` is not shown, and only `QR-Code` based Singing is made, which is fine, but want to remove the initial `Install Browser extension` message if it's not really detecting it and using it.

**Comment by alexandratran** [comment]
duplicates #664
