### ISSUE TITLE
metamask wallet and Coinbase wallet and Safeheron wallet co-installation

### ISSUE THREAD

**Issue by charles-lpd** [MetaMask/metamask-docs#672]
Browser: Google chrome
System macOs

When getting window.ethereum
<img width="357" alt="image" src="https://user-images.githubusercontent.com/90810762/222357047-ccfb49e9-c530-4656-9516-0988bb696b58.png">
will appear  "providerMap & providers"

but 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/90810762/222357458-caea2459-33b7-4579-963e-6137c8c903d5.png">

Safeheron wallet will overwrite metamask wallet

but 
There are three wallets in providers provide
<img width="361" alt="image" src="https://user-images.githubusercontent.com/90810762/222358359-d397b10b-ad69-4d0a-bcbe-b6b0ea1e758e.png">

but 
I can't get the correct MetaMask with isMetamask
Because Safeheron provide also contains isMetaMask
I'm having a hard time
<img width="347" alt="image" src="https://user-images.githubusercontent.com/90810762/222360167-d0220afb-4571-4c8d-8c28-ae524ff29b1c.png">

Is there any way to get it right?

**Comment by httpJunkie** [comment]
My suggestion is to implement EIP-6963. Are you using React?

I am writing about the subject here: [A Guide to EIP-6963 for React Developers
](https://hackmd.io/LlaWBgdBTTueAdEc0u7xRA)

I have demo code for that article and implementing with VireJS (React + TypeScript) here:
[vite-react-ts-eip-6963](https://github.com/MetaMask/vite-react-ts-eip-6963)

So, I have had a similar issue as you with Rabby Wallet. So for instance I test a lot of my applications with the follwing wallets installed:

- MetaMask
- MetaMask Flask
- Coinbase
- Rabby (in your case SafeHeron *which I don't know about)


The issue with Rabby wallet is that it identifies itself using: `isMetaMask: true`
Therefore if installed websites might show you a MetaMask icon and then when you connect it doesn't connect to MetaMask but this other wallet instead.

The best solution to ensure this doesn't happen is to implement EIP-6963 or use a library like WAGMI that uses EIP-6963 in which I have wrote about in the article above. If you build in web3, and have not explored EIP-6963 which is an alternative to using `window.ethereum` and negating the ethereum clobbering from various installed wallets. My article above will be a good read. Should only take 15 minutes and links to the EIP.

With my the EIP-6963 integration you will get a very clear UI/UX like this:
![](https://imgur.com/9ucYAB2.gif)
