### ISSUE TITLE
MetaMask Unity SDK Contract Interaction

### ISSUE THREAD

**Issue by YusufBesim** [MetaMask/metamask-docs#678]
Hello,

I have tried many ways to interact with my contract.
I did it 2 ways but it is not easy and useful with SDK. 
Please add an example to documentation

Thank you.

**Comment by alexandratran** [comment]
@YusufBesim is this still an issue for you, and can you provide examples of what you're using that's not working? [Here](https://docs.metamask.io/wallet/how-to/use-sdk/gaming/unity) are the updated Unity SDK docs.
