### ISSUE TITLE
[QUESTION] Do you know the params of a personal_sign request for Unity?

### ISSUE THREAD

**Issue by Ermys-Code** [MetaMask/metamask-docs#681]
I am trying to send a personal_sign request to the metamask mobile app from Unity, and it always return me the same error:

System.Exception: {"code":-32603,"message":"Invalid \"from\" address: undefined must be a valid string.","data":{"originalError":{}}}

But I checked the address and is a totally valid string (I can do other request without problems with it).
The params that i use are:
- address: 0xa5dea3a1d5f503f153de9acd94f565df04e6f224
- message: an hex-encoded UTF-8 message
 
All help is apreciated :D

**Comment by alexandratran** [comment]
@Ermys-Code Do you still have an issue with this? Did you take a look at the example from the docs? https://docs.metamask.io/wallet/how-to/sign-data/#use-personal_sign
