### ISSUE TITLE
Document ways to polyfill Buffer

### ISSUE THREAD

**Issue by ritave** [MetaMask/metamask-docs#682]
A recurring problem with people building Snaps is that they use third party libraries which use Node's `Buffer`. Since we removed that polyfill, we get recurring reports about third party libraries not working.

Please document the best way to include `Buffer` in snaps, and maybe state common errors resulting from it's lack for SEO.

**Comment by ziad-saab** [comment]
This will be made unnecessary by https://github.com/MetaMask/template-snap-monorepo/pull/35
