### ISSUE TITLE
Improve guidelines for using wallet_getPermissions to get all accounts shared by the user

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#699]
@vandan commented on [Thu Apr 13 2023](https://github.com/MetaMask/mm-docs-v2/issues/117)

One point of confusion we have today is that the `eth_requestAccounts` method includes at most one account in the array that's returned (we plan to change this limitation). In the meantime, if the user granted permissions for more than one account, developers can get the full list by using the `wallet_getPermissions` method.
While there is a Note with a hint in [this section of the docs](https://docs.metamask.io/wallet/get-started/access-accounts#create-a-connect-button), developers may have trouble figuring out how to get all accounts from this method.

See more detail about how using this method can be confusing for developers [in this slack thread](https://consensys.slack.com/archives/C027M10HGEA/p1681404332313829). This question has come in a few conversations with developers.

At the same time, we have to be explicit about our guarantees around the `wallet_getPermissions` API. Specifically, we should not guarantee anything about the value of individual caveats in the caveat array, or the value of the parentCapability field, which are going to be subject to change in the future.

**Comment by alexandratran** [comment]
Fixed by https://github.com/MetaMask/metamask-docs/pull/773
