### ISSUE TITLE
Clicking on the `ethereum API` link leads to a 404 page

### ISSUE THREAD

**Issue by inje** [MetaMask/metamask-docs#7]
This issue refers to the link at the [bottom of this page](https://metamask.github.io/metamask-docs/Examples/Low_Level_Ether_Transfer) highlighted as `ethereum API`.

## Screenshot of the link
<img width="808" alt="screen shot 2019-03-03 at 11 10 44 pm" src="https://user-images.githubusercontent.com/4149515/53716510-0cfccd00-3e0a-11e9-8ebf-aebf2fb768d9.png">

Which leads to https://metamask.github.io/metamask-docs/Examples/API_Reference
## 404 Page
<img width="1039" alt="screen shot 2019-03-03 at 11 15 08 pm" src="https://user-images.githubusercontent.com/4149515/53716590-3d446b80-3e0a-11e9-97a2-874e19be4d21.png">

May be what @marcuswin was referring to in his issue here #4

**Comment by Gudahtt** [comment]
This was fixed in #11
