### ISSUE TITLE
Add header to the right-hand table of content

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#701]
@eriknson commented on [Fri Mar 24 2023](https://github.com/MetaMask/mm-docs-v2/issues/76)

<img width="729" alt="Suggested" src="https://user-images.githubusercontent.com/34306844/227571440-0f4a5101-1d3f-4437-8795-4e4e6c94aa12.png">

**Current design for comparison**
<img width="729" alt="Suggested-1" src="https://user-images.githubusercontent.com/34306844/227571433-061ed494-3173-4a0a-8ef1-da0abf8703e3.png">

---

@alexandratran commented on [Tue Mar 28 2023](https://github.com/MetaMask/mm-docs-v2/issues/76#issuecomment-1487227503)

This doesn't seem possible with Docusaurus (at least without some custom plugin): https://docusaurus.io/docs/markdown-features/toc.

---

@ziad-saab commented on [Wed Mar 29 2023](https://github.com/MetaMask/mm-docs-v2/issues/76#issuecomment-1489069586)

it's possible. We have to create a customized component: https://docusaurus.io/docs/swizzling

---

@rekmarks commented on [Wed Mar 29 2023](https://github.com/MetaMask/mm-docs-v2/issues/76#issuecomment-1489723530)

I don't see why we should close this issue.

**Comment by alexandratran** [comment]
This is fixed in the upcoming new design.
