### ISSUE TITLE
Incorporate basic feedback into the docs site

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#702]
@vandan commented on [Wed Mar 22 2023](https://github.com/MetaMask/mm-docs-v2/issues/67)

Feedback mechanisms:

- "Did you find this useful" widget
- Feedback button
- Surveys (Stretch)

We can implement this feature with GetFeedback (and Momentive):
[Here is the info](https://help.surveymonkey.com/en/getfeedback/channels/web-buttons/#creating) for installing a "Feedback" button.
[Here is the info](https://help.surveymonkey.com/en/getfeedback/channels/web-widgets/) for installing in page widgets (e.g. did you find this useful :+1: :-1: )
[Here is the info](https://help.surveymonkey.com/en/getfeedback/channels/web-overlay/) for installing a pop-up survey (for NPS etc)

---

@vandan commented on [Wed Mar 22 2023](https://github.com/MetaMask/mm-docs-v2/issues/67#issuecomment-1480394891)

We need access to GetFeedback & Momentive in order to generate the code snippet for this feature.

---

@httpJunkie commented on [Fri Apr 07 2023](https://github.com/MetaMask/mm-docs-v2/issues/67#issuecomment-1500286621)

Where would we like these forms to posy to?

Why not build a react component that uses a typeForm? 

https://medium.com/typeforms-engineering-blog/building-typeform-react-embed-sdk-e3985efccfc5

**Comment by dgarcia360** [comment]
Hi @vandan ! 

I found this issue while searching for "feedback widget" on GitHub.

I'm building [PushFeedback](https://pushfeedback.com), a feedback widget tailored for docs sites that integrates well with Docusaurus.

![Feedback for docs](https://github.com/o1-labs/docs2/assets/9107969/1efdd2f1-3bba-40b9-a441-6137b0c14448)

> The current thumbs-up and down implementation is not very effective in terms of understanding what went wrong in a specific document.

As a MetaMask user, I'd love to see it installed in the docs! We have a free plan for open-source project in exchange of keeping the widget branding. If you're interested in exploring integrating PushFeedback, please [sign up for an account](https://app.pushfeedback.com/accounts/signup/) and let me know to remove the limitations for your project. 

Additionally, I'd be more than happy to assist with a pull request to integrate the [Docusaurus extension](https://docs.pushfeedback.com/installation/docusaurus).

Looking forward to hearing from you!

**Comment by alexandratran** [comment]
In-page feedback widget added in #962 
SDK pop-up survey added in #722 
Dev recruitment form will be linked from the banner added in #966 (and footer) once the form is ready

We're still awaiting an answer on whether we can collect emails and how to do that, while being data compliant.
