### ISSUE TITLE
Incorporate better analytics into the docs

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#705]
@vandan commented on [Mon Feb 27 2023](https://github.com/MetaMask/mm-docs-v2/issues/45)

For increased flexibility and consistency with MetaMetrics we should implement event tracking via Segment.
[Event Metrics for New Products](https://www.notion.so/Event-Metrics-for-New-Products-fb69690757a249a49f13584b77b39515#6b85f576f2a54180b72ffe56c3b6d613) doc provided the guidelines for setting this up.

@vandan has the code snippet from John for adding staging and prod event tracking destinations.

---

@vandan commented on [Wed Mar 08 2023](https://github.com/MetaMask/mm-docs-v2/issues/45#issuecomment-1461050428)

@vandan may need to confirm if there are any additional considerations for adding Segment analytics to our tech docs pages (Cookie tracking consent, GDPR, etc.).

---

@vandan commented on [Wed Apr 12 2023](https://github.com/MetaMask/mm-docs-v2/issues/45#issuecomment-1505952375)

Awaiting cookie consent widget & guidelines from legal.

**Comment by vandan** [comment]
Planning to incorporate Segment.
There is a plugin I'm considering: https://github.com/xer0x/docusaurus-plugin-segment
Let me know if anyone has experience using it or concerns with that approach.

**Comment by kenhkan** [comment]
From standup: Vandan to create follow-up ticket on long-term solution.
