### ISSUE TITLE
Improve snaps cross-fetch documentation

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#711]
@FrederikBolding commented on [Fri Apr 14 2023](https://github.com/MetaMask/mm-docs-v2/issues/118)

With a recent snaps platform update `fetch` has been hardened and the `cross-fetch` patching documentation needs to be updated.

![image](https://user-images.githubusercontent.com/1561200/232044294-d36faafd-3d08-49bd-a841-1ad6425265e3.png)

**Comment by FrederikBolding** [comment]
Actually this doesn't seem to be necessary anyway. The current example we have seems to work on the latest version. Will close for now.
