### ISSUE TITLE
Not all images in docs have a BG color

### ISSUE THREAD

**Issue by httpJunkie** [MetaMask/metamask-docs#725]
We have images like the following:
https://docs.metamask.io/wallet/concepts/sdk-connections/

<img width="400" alt="no-bg-color" src="https://user-images.githubusercontent.com/4899480/233723502-897a0a10-04fc-45e6-a505-e4b250ff62de.png">

They do not have a BG color and therefore do not display correctly on dark mode.

Beyond fixing this issue, it should be mandatory for all images to have a white or `#1b1b1d` color background. We also need to set a style on images to have rounded corners using `0.4rem` (same as `--ifm-global-radius`) used for code blocks.

If all images have a background equal to the light or dark background and a radius applied, they will look good on both light and dark mode. 

| Dark Mode  | Light Mode |
| ------------- | ------------- |
| <img width="250" alt="dark" src="https://user-images.githubusercontent.com/4899480/233724621-71aaa041-b0db-4ab9-983a-239e24640cd9.png">  | <img width="250" alt="light" src="https://user-images.githubusercontent.com/4899480/233724626-25ad83f4-ff38-422f-89c3-e0338ae39716.png">  |

**Comment by vandan** [comment]
@alexandratran wondering if some of this should go into a set of documentation style guidelines.
