### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by ZenChains** [MetaMask/metamask-docs#754]
"react-native": "0.71.7",
    "react": "18.2.0",
    "@metamask/sdk": "^0.2.2",
    "typescript": "4.8.4"。

help，new MetaMaskSDK() faild。
TypeError: Cannot read property 'slice' of undefined, js engine: hermes

**Comment by ziad-saab** [comment]
@ZenChains thanks for the issue report. Please re-post this in the [`metamask-sdk` issues](https://github.com/MetaMask/metamask-sdk/issues) instead. I will close this one for you.
