### ISSUE TITLE
Document how to connect to a snap, and how to find out whether a snap is installed

### ISSUE THREAD

**Issue by ziad-saab** [MetaMask/metamask-docs#760]
The JSON-RPC API in the docs shows `wallet_getSnaps` and `wallet_getSnaps`, but we should have more complete examples of each in the "How To" section of the docs.

**Comment by ziad-saab** [comment]
make sure to correct the documentation that says that `wallet_invokeSnap` can only be called by websites.

**Comment by kenhkan** [comment]
From standup: Christian to help with this while Ziad is busy with the Accounts team
