### ISSUE TITLE
Suggestion: Divide the signing methods page into 2 sections: Recommended and Deprecated (or Current and Deprecated)

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#764]
The information presented on this page is chronological and accurate but it is not the most useful way to present the information to a developer who just wants to find the best ways to use signing right now: 
https://docs.metamask.io/wallet/concepts/signing-methods

It makes sense to present accurate information but I have an idea on how this could be rewritten to prioritize giving the most useful information first. Make two sections, the first section being "recommended" or "current" (not sure what the best term would be) and the second section "deprecated." 

So the first section would have two subheads, 1. personal_sign and 2. eth_signTypedData_v4, and the second would have everything else with a big disclaimer that all these methods are not recommended to be used.

**Comment by alexandratran** [comment]
@Montoya The top of this page links to the [how to guide on signing data page](https://docs.metamask.io/wallet/how-to/sign-data/), which walks you through using only the recommended signing methods. The assumption is that people would go to that page in the how to section for a clear how to sign guide, and they would go to the [conceptual signing page](https://docs.metamask.io/wallet/concepts/signing-methods/) you referenced for more background information/context.

With that in mind, do you still think the conceptual page should be rearranged? Is the how to page easy to miss?

**Comment by MadelineMurray** [comment]
I think the level of effort to update the reference pages into supported and deprecated makes this change worthwhile.  My rationale for that is that experienced users will may not leave the reference pages to find what they want eg, if they've been using these APIs for years, they may not follow the path to the how to page.
