### ISSUE TITLE
`yarn global add` is not supported in yarn v2 or v3

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#775]
[In the docs for the snaps-cli](https://docs.metamask.io/snaps/get-started/install-snaps/#install-the-snaps-cli) we tell users to use npm or yarn to install the snaps cli globally, but this has been deprecated in yarn: https://yarnpkg.com/getting-started/migration#use-yarn-dlx-instead-of-yarn-global

We should just tell users to use npm and drop the mention of yarn, or include instructions for using `yarn dlx`.

**Comment by ziad-saab** [comment]
@Montoya can you please point to the docs section

**Comment by ziad-saab** [comment]
> @Montoya can you please point to the docs section

found it
