### ISSUE TITLE
Bug: Logo when scrolling

### ISSUE THREAD

**Issue by eriknson** [MetaMask/metamask-docs#776]
<img width="694" alt="Screenshot 2023-06-02 at 13 22 25" src="https://github.com/MetaMask/metamask-docs/assets/34306844/02a1ff15-efa5-4864-a80a-e8ae67379683">

**Comment by eriknson** [comment]
Since the header (with the logo) animates up, I'm not sure we need to display the documentation-suffix here.

**Comment by ziad-saab** [comment]
Looks like the URL in your screenshot is showing a different behavior that our live URL at https://docs.metamask.io/wallet

I'm not sure why, but I'm not able to reproduce this on the live site. I feel like you might be looking at an outdated version.

**Comment by eriknson** [comment]
Ye, you're right, can't seem to reproduce this in production so closing this.
