### ISSUE TITLE
metamask.github.io/metamask-docs doesn't get the automatic vuepress updates, probably due to the dns redirect

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-docs#78]

**Comment by BboyAkers** [comment]
Anything I can do from an application standpoint to help out with this?

**Comment by jennypollack** [comment]
we also noticed that the codepen examples don't appear on the metamask.githubi.io/metamask-docs version

**Comment by BboyAkers** [comment]
Created an issue and going to work on the conversion https://github.com/MetaMask/metamask-docs/issues/89 should have a pull request in a day or two

**Comment by BboyAkers** [comment]
closing due to merged pull request(s)

**Comment by jennypollack** [comment]
on the metamask.github.io version:
in console: ```manifest.json:1 Manifest: property 'start_url' ignored, should be same origin as document.```

**Comment by BboyAkers** [comment]
Redirects to https://docs.metamask.io/guide/ now. Closing 🙂
