### ISSUE TITLE
better styling for json-schema-form usage (aligment of buttons)

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-docs#786]

**Comment by shanejonas** [comment]
good example of this is `addEthereumChain`

its awesome it provides some great features like moving array items around but doesnt look that great right now:


![image](https://github.com/MetaMask/metamask-docs/assets/364566/956df24c-b3c1-4181-9c63-dbb97218da98)

**Comment by BelfordZ** [comment]
done in latest preview of https://github.com/MetaMask/metamask-docs/pull/811
