### ISSUE TITLE
Add images for social media cards

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#800]
When I share a page from the docs site on social media, I would like the image preview to be filled with something on-brand

<img width="528" alt="Screenshot 2023-06-07 at 11 35 00 AM" src="https://github.com/MetaMask/metamask-docs/assets/19909/623f40d7-ae8b-45d2-a921-f54faca5f65b">

Examples of image tags to be included in the header to show up in cards like this: 

https://blog.hubspot.com/marketing/open-graph-tags-facebook-twitter-linkedin

Twitter's card validator for testing: 

https://cards-dev.twitter.com/validator

**Comment by eriknson** [comment]
<img width="1200" alt="Twitter post - 1" src="https://github.com/MetaMask/metamask-docs/assets/34306844/c9d714c7-f83f-4fb1-b951-7fbddec87745">
<img width="1200" alt="Twitter post - 2" src="https://github.com/MetaMask/metamask-docs/assets/34306844/64f1c2ea-677f-44ca-bd81-103213f98c8c">
<img width="1200" alt="Twitter post - 3" src="https://github.com/MetaMask/metamask-docs/assets/34306844/39e4e9f4-f255-40ad-919b-917784c74e4f">

**Comment by alexandratran** [comment]
@BelfordZ wrote on #814:

See https://ogp.me/ for more details.

Links shared in various places should have a nice look to them. Heres an example of what it currently looks like when you link the docs on twitter:

![image](https://github.com/MetaMask/metamask-docs/assets/1787231/d162c099-6d38-470f-a30e-893e3d7cbf92)

- using docusarus global https://docusaurus.io/docs/seo#global-metadata would be a good start
- using same meta tags as metamask.io would be a good start as well.

**Comment by joaniefromtheblock** [comment]
https://www.opengraph.xyz/url/https%3A%2F%2Fdocs.metamask.io
