### ISSUE TITLE
Improve the "Snaps JSON-RPC API" sub-section

### ISSUE THREAD

**Issue by ziad-saab** [MetaMask/metamask-docs#841]
AC:

- The "Reference" section in the navigation menu is automatically expanded
- The section is renamed to "Snaps API"
- The `snap` global is documented
- The `ethereum` global is documented, including its differences with a "regular" Ethereum Provider -- e.g. the `eth_requestAccounts` method isn't available
- The differentiation between "restricted" and "unrestricted" methods is removed

**Comment by alexandratran** [comment]
Relates to #805
