### ISSUE TITLE
Incorporate cookie consent into the developer website

### ISSUE THREAD

**Issue by vandan** [MetaMask/metamask-docs#851]
In order to improve MetaMetrics analytics and allow for developer feedback, we need to incorporate a cookie consent widget into the developer docs site.

Here's the code snippet to be included across the site:
`<script src="https://cmp.osano.com/AzZMxHTbQDOQD8c1J/a2e89f0e-f467-4542-bfea-30ea2c1a6648/osano.js"></script>`

**Comment by kenhkan** [comment]
From standup:
- We will show the cookie icon all the time on the page as the first step. Then iterate towards having something similar to consensys.io
- Should "Targeted Advertising" be on by default?

**Comment by vandan** [comment]
@shanejonas I think we should proceed with the existing cookie consent script. The issue with "Targeted Advertising" would require us to incorporate a different script for MetaMask (rather than sharing across ConsenSys), which I believe would be reasonable to adjust when we also remove the "floating action button" (persistent cookie icon).
In the interim, people who are concerned with it could always disable the "Targeted Advertising" cookie consent setting.

**Comment by vandan** [comment]
Relates to https://github.com/Consensys/dx-team/issues/1518

**Comment by vandan** [comment]
Resolve through this PR: https://github.com/MetaMask/metamask-docs/pull/872
