### ISSUE TITLE
Create Unity SDK tutorial

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#867]
Create an end-to-end tutorial on using MM SDK in a Unity project.

**Comment by helgi-outerlynx** [comment]
Any timeline as to when this tutorial can be out? 
Right now, the SDK is barely usable with how little information is given and how much time it takes to grasp what's going on.

**Comment by alexandratran** [comment]
@helgi-outerlynx Unfortunately it might be a while until we can create a full end-to-end tutorial, because we're currently still hiring for a Unity developer relations position.

For now, please make sure you have downloaded the latest Unity SDK version and that you've looked at the demo, steps and FAQs on the [Unity guide](https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/gaming/unity/). You can also see [this demo game](https://assetstore.unity.com/packages/decentralization/demo-game-dragon-crasher-with-metamask-sdk-infura-and-truffle-249789) that uses the sdk.

If you have specific issues that you're running into at any step, please raise an issue on the [SDK repo](https://github.com/MetaMask/metamask-sdk/issues) and an engineer will address it.

**Comment by Montoya** [comment]
Closing, will revisit depending on future SDK plans
