### ISSUE TITLE
Document the eth_accounts response

### ISSUE THREAD

**Issue by pedrolucasp** [MetaMask/metamask-docs#899]
The guide for connecting to MetaMask tells us that one of the first things we need to do is to request the user accounts. But in any of the links (even the documentation for the `eth_requestAccounts` RPC method), it gives us any sort of documentation of >what< or how is that response data structured, which objects and fields are returned, etc.

It even gives a small glimpse of the data, like this footnote:

>eth_accounts now returns the full list of accounts for which the user has permitted access to. Previously, eth_accounts returned at most one account in the accounts array. The first account in the array will always be considered the user's "selected" account.

But in any way, it describes *what* data is returned other than an array. Is that a list of strings, or is that an object filled with information, there's no way to know. Maybe there is documentation for this response somewhere else, but I haven't dug enough to find it out, so maybe a link to that documentation would be good.

**Comment by alexandratran** [comment]
Hi @pedrolucasp! Thanks for pointing out this out. In the connect to MetaMask page, we should be linking to the `eth_requestAccounts` documentation in the interactive API playground: https://docs.metamask.io/wallet/reference/eth_requestaccounts/

There you can see that the result is an array of strings. You can even test the method out in your browser to see an example.

I'll add it to the backlog to update that link and also to add some missing examples to the API playground.
