### ISSUE TITLE
How To guide for integrating a dapp with the Starknet Snap

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-docs#920]
The Starknet Snap dev team has a guide for connecting to the Starknet Snap with documentation for all the methods exposed by the Snap. We could publish this in the docs site under the How To section or as a tutorial...

**Comment by reetbatra** [comment]
May I work on this please?

**Comment by Montoya** [comment]
Yes, you could create a branch and add the documentation as a sub-page under https://docs.metamask.io/snaps/how-to/connect-to-a-snap/

**Comment by reetbatra** [comment]
if i am not wrong do you mean the readme file of this https://github.com/Consensys/starknet-snap
shall I add a link to this instead of creating a sub-page?

**Comment by joaniefromtheblock** [comment]
This has been resolved with the release of the [Starknet (non-EVM) work](https://github.com/MetaMask/metamask-docs/pull/1509)
