### ISSUE TITLE
Documentation is misleading 

### ISSUE THREAD

**Issue by pociej** [MetaMask/metamask-docs#921]
here https://docs.metamask.io/wallet/how-to/connect/detect-metamask/#use-metamaskdetect-provider 
one can find. 

if (typeof window.ethereum !== 'undefined') {
  console.log('MetaMask is installed!');
}

Which suggest that it is way to detect if metamask plugin is installed or not. This is obviously false use sdk addes `window.ethereum` ( why btw? )

**Comment by alexandratran** [comment]
@pociej Can you clarify your question? The page you link also contains a tip: "To differentiate MetaMask from other Ethereum-compatible browsers, you can detect MetaMask using the [`window.ethereum.isMetaMask`](https://docs.metamask.io/wallet/reference/provider-api/#windowethereumismetamask) property."

Also, the SDK uses the same provider object and you can call `window.ethereum` or just `ethereum` the same way when using the SDK.
