### ISSUE TITLE
Fix global React dapp tutorial

### ISSUE THREAD

**Issue by alexandratran** [MetaMask/metamask-docs#930]
From a Slack message:

> Hi team, I'm not sure if this is the right channel, but a user reported a possible error with our React dapp integration code/tutorial here: https://docs.metamask.io/wallet/tutorials/react-dapp-global-state/
>> Code wise, the error is not huge, however it provides some error. Once the user is connected with MetaMask there is the possibility to view the connected address on Etherscan. In this tutorial, however, an object is passed to Etherscan instead of the actual connected address. What now has to be changed in order for the code to work as intended, one has to change just one line in the code. Inside the Navigation.tsx file in line 27 the new code has to look like this: "href={[https://etherscan.io/address/${wallet.accounts[0]}](https://etherscan.io/address/$%7Bwallet.accounts[0]%7D)}". What has changed here is that instead of the object "${wallet}" now the current account "${wallet.accounts[0]}" is taken into consideration and the error is fixed.
>> If you would like to view the new code, I posted it on my personal github account with some slight changes https://github.com/MikePawel/MetaMask-global-state

**Comment by ATREAY** [comment]
hey @alexandratran, can I work on this issue if you are not already working on it?

**Comment by alexandratran** [comment]
@ATREAY assigned!

**Comment by ATREAY** [comment]
Hey @alexandratran, I've made the required changes. Please take a look when you have a moment.
